### ISSUE TITLE
Connecting to Redis during package discovery

### ISSUE THREAD

**Issue by rihardssceredins** [laravel/telescope#1023]
- Telescope Version: v4.4.4
- Laravel Version: v8.29.0
- PHP Version: 8.0.2
- Database Driver & Version:

### Description:
Hey,

Is it by design that Telescope is trying to connect to Redis during package discovery when running `composer install`? 🤔
I'm using docker-compose for my local environment and it's really driving me nuts that I've to start all services before I can install composer packages or switch a branch (I've a post checkout & post merge git hook to run `composer install` automatically). 😬

<img width="1107" alt="Screenshot 2021-03-04 at 09 46 05" src="https://user-images.githubusercontent.com/23099574/109929536-3d182880-7ccf-11eb-869a-e2f5c56e086e.png">

**Comment by driesvints** [comment]
Can you post a full stacktrace so we can pinpoint the line where Telescope is trying to connect to Redis?

**Comment by rihardssceredins** [comment]
@driesvints sorry, didn't think of it before. Here you go:

```
[2021-03-04 11:16:57] local.ERROR: Connection refused {"exception":"[object] (RedisException(code: 0): Connection refused at /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:142)
[stacktrace]
#0 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(142): Redis->connect('127.0.0.1', 6379, 0, NULL, 0, 0)
#1 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(84): Illuminate\\Redis\\Connectors\\PhpRedisConnector->establishConnection(Object(Redis), Array)
#2 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}(Object(Redis))
#3 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(109): tap(Object(Redis), Object(Closure))
#4 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(28): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient(Array)
#5 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(32): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#6 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(110): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect(Array, Array)
#7 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(90): Illuminate\\Redis\\RedisManager->resolve('cache')
#8 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(249): Illuminate\\Redis\\RedisManager->connection('cache')
#9 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(61): Illuminate\\Cache\\RedisStore->connection()
#10 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(97): Illuminate\\Cache\\RedisStore->get('telescope:dump-...')
#11 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(406): Illuminate\\Cache\\Repository->get('telescope:dump-...')
#12 /Users/rihardssceredins/Code/api-diet/vendor/laravel/telescope/src/Watchers/DumpWatcher.php(43): Illuminate\\Cache\\CacheManager->__call('get', Array)
#13 /Users/rihardssceredins/Code/api-diet/vendor/laravel/telescope/src/RegistersWatchers.php(48): Laravel\\Telescope\\Watchers\\DumpWatcher->register(Object(Illuminate\\Foundation\\Application))
#14 /Users/rihardssceredins/Code/api-diet/vendor/laravel/telescope/src/Telescope.php(143): Laravel\\Telescope\\Telescope::registerWatchers(Object(Illuminate\\Foundation\\Application))
#15 /Users/rihardssceredins/Code/api-diet/vendor/laravel/telescope/src/TelescopeServiceProvider.php(31): Laravel\\Telescope\\Telescope::start(Object(Illuminate\\Foundation\\Application))
#16 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Telescope\\TelescopeServiceProvider->boot()
#17 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#19 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#20 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#21 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(914): Illuminate\\Container\\Container->call(Array)
#22 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(895): Illuminate\\Foundation\\Application->bootProvider(Object(Laravel\\Telescope\\TelescopeServiceProvider))
#23 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Laravel\\Telescope\\TelescopeServiceProvider), 25)
#24 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(896): array_walk(Array, Object(Closure))
#25 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#26 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#27 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#28 /Users/rihardssceredins/Code/api-diet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#29 /Users/rihardssceredins/Code/api-diet/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 {main}
```

**Comment by driesvints** [comment]
@rihardssceredins if you move these lines: https://github.com/laravel/telescope/blob/4.x/src/Watchers/DumpWatcher.php#L43-L45

To right above here: https://github.com/laravel/telescope/blob/4.x/src/Watchers/DumpWatcher.php#L51

Does that fixes your issue?

**Comment by rihardssceredins** [comment]
@driesvints works like a charm, thank you. ✨ Opened a PR: https://github.com/laravel/telescope/pull/1025

**Comment by driesvints** [comment]
cool, thanks!

**Comment by wsamoht** [comment]
Since the original fix for this was reverted due to the issue it caused in #1026 and #1028, a temporary solution that I found is to just disable Telescope if Laravel is running in the console. I have Telescope set up for a [Local Only Solution](https://laravel.com/docs/8.x/telescope#local-only-installation) with auto discovery off.

**STEP 1**
Rename `App/Providers/TelescopeServiceProvider.php` to `TelescopeApplicationServiceProvider.php`

```php
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Gate;
use Laravel\Telescope\IncomingEntry;
use Laravel\Telescope\Telescope;
use Laravel\Telescope\TelescopeApplicationServiceProvider as LaravelTelescopeApplicationServiceProvider;

class TelescopeApplicationServiceProvider extends LaravelTelescopeApplicationServiceProvider
{
  // No changes to code here. Just need to update the class name and the class being extended.
}
```

**STEP 2**
Create a new class `App/Providers/TelescopeServiceProvider.php`

```php
<?php

namespace App\Providers;

use Laravel\Telescope\TelescopeServiceProvider as LaravelTelescopeServiceProvider;

class TelescopeServiceProvider extends LaravelTelescopeServiceProvider
{
    public function register()
    {
        parent::register();

        // Temporary fix for https://github.com/laravel/telescope/issues/1023
        if ($this->app->runningInConsole()) {
            config(['telescope.enabled' => false]);
        }
    }
}
```

**STEP 3**
Update `App/Providers/AppServiceProvider.php`.

```php
public function register()
{
    if ($this->app->environment('local')) {
        $this->app->register(TelescopeServiceProvider::class);
        $this->app->register(TelescopeApplicationServiceProvider::class);
    }
}
```

**Other Comments**
I first tried just disabling the `DumpWatcher` but Telescope uses the cache other places that were still causing it to throw the connection exception.

```php
config(['telescope.watchers.' . \Laravel\Telescope\Watchers\DumpWatcher::class => false]);
```

I hope this helps anyone else who runs into this issue!

**Comment by njoguamos** [comment]
@wsamoht Your solution worked form me


```php

class TelescopeServiceProvider extends TelescopeApplicationServiceProvider
{
    public function register()
    {
        // ...

        if ($this->app->runningInConsole()) {
            config(['telescope.enabled' => false]);
        }
    }

   // ...

}
```

**Comment by ahmadmmughal** [comment]
Encountered this error today and simply adding this snippet:
`if ($this->app->runningInConsole()) {
            config(['telescope.enabled' => false]);
        }`
in the already existing TelescopeServiceProvider register method worked.

Thanks @njoguamos and @wsamoht!

**Comment by satya-kr** [comment]
use this it will not break your development telescope track 

`if ($this->app->environment('local') && $this->app->runningInConsole()) {
            config(['telescope.enabled' => false]);
 }`
