### ISSUE TITLE
Undefined variable: assetsAreCurrent

### ISSUE THREAD

**Issue by keizah7** [laravel/telescope#1077]
- Telescope Version: 4.4.10
- Laravel Version: 8.46.0
- PHP Version: 7.4.15
- Database Driver & Version: mysql  Ver 8.0.23

### Description:
```
[2021-06-15 09:22:24] production.ERROR: Undefined variable: assetsAreCurrent (View: /home/erp/erp.jammi.lt/vendor/laravel/telescope/resources/views/layout.blade.php) {"view":{"view":"/home/erp/erp.jammi.lt/vendor/laravel/telescope/src/../resources/views/layout.blade.php","data":{"errors":"<pre class=sf-dump id=sf-dump-1744960686 data-indent-pad=\"  \"><span class=sf-dump-note>Illuminate\\Support\\ViewErrorBag</span> {<a class=sf-dump-ref>#738</a><samp data-depth=1 class=sf-dump-expanded>
  #<span class=sf-dump-protected title=\"Protected property\">bags</span>: []
</samp>}
</pre><script>Sfdump(\"sf-dump-1744960686\", {\"maxDepth\":3,\"maxStringLength\":160})</script>
","cssFile":"<pre class=sf-dump id=sf-dump-2014694114 data-indent-pad=\"  \">\"<span class=sf-dump-str title=\"12 characters\">app-dark.css</span>\"
</pre><script>Sfdump(\"sf-dump-2014694114\", {\"maxDepth\":3,\"maxStringLength\":160})</script>
","telescopeScriptVariables":"<pre class=sf-dump id=sf-dump-1877559881 data-indent-pad=\"  \"><span class=sf-dump-note>array:3</span> [<samp data-depth=1 class=sf-dump-expanded>
  \"<span class=sf-dump-key>path</span>\" => \"<span class=sf-dump-str title=\"9 characters\">telescope</span>\"
  \"<span class=sf-dump-key>timezone</span>\" => \"<span class=sf-dump-str title=\"14 characters\">Europe/Vilnius</span>\"
  \"<span class=sf-dump-key>recording</span>\" => <span class=sf-dump-const>true</span>
</samp>]
</pre><script>Sfdump(\"sf-dump-1877559881\", {\"maxDepth\":3,\"maxStringLength\":160})</script>
"}},"userId":9,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): Undefined variable: assetsAreCurrent (View: /home/erp/erp.jammi.lt/vendor/laravel/telescope/resources/views/layout.blade.php) at /home/erp/erp.jammi.lt/vendor/laravel/telescope/src/../resources/views/layout.blade.php:204)
[stacktrace]
#0 /home/erp/erp.jammi.lt/vendor/laravel/telescope/src/../resources/views/layout.blade.php(204): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/home/erp/erp.j...')
#2 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#3 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#4 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#5 /home/erp/erp.jammi.lt/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\\View\\Engines\\CompilerEngine->get()
#6 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/View/View.php(139): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get()
#7 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#8 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#9 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#10 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#11 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(793): Illuminate\\Http\\Response->__construct()
#12 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(763): Illuminate\\Routing\\Router::toResponse()
#13 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Router->prepareResponse()
#14 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#15 /home/erp/erp.jammi.lt/vendor/laravel/telescope/src/Http/Middleware/Authorize.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Telescope\\Http\\Middleware\\Authorize->handle()
#17 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#19 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#21 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#23 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#25 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#26 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#28 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#30 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#32 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#33 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#34 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#35 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#36 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#37 /home/erp/erp.jammi.lt/nova/src/Http/Middleware/ServeNova.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle()
#39 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#41 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#42 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#44 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#45 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#47 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#49 /home/erp/erp.jammi.lt/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#51 /home/erp/erp.jammi.lt/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#53 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#55 /home/erp/erp.jammi.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#56 /home/erp/erp.jammi.lt/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#57 {main}
```

### Steps To Reproduce:
https://app.url/telescope

**Comment by driesvints** [comment]
Clear your cached views and make sure any published telescope assets are up to date
