### ISSUE TITLE
Dump watcher not working php_network_getaddresses: getaddrinfo failed

### ISSUE THREAD

**Issue by Eldair** [laravel/telescope#1107]
- Telescope Version: 4.6.0
- Laravel Version: 8.52.0
- PHP Version: 8
- Database Driver & Version: mysql:8.0
- Using docker with lando

### Description:
Whenever telescope path is open I constantly get these errors in log file and dump watcher doesn't work. Everything else works, including Redis (and cache) watcher which is why this is strange.
```
[2021-07-30 14:01:18] local.ERROR: php_network_getaddresses: getaddrinfo failed: Name or service not known {"exception":"[object] (RedisException(code: 0): php_network_getaddresses: getaddrinfo failed: Name or service not known at /home/eldair/code/project/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:141)
[stacktrace]
#0 /home/eldair/code/project/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(141): Redis->connect()
#1 /home/eldair/code/project/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(84): Illuminate\\Redis\\Connectors\\PhpRedisConnector->establishConnection()
#2 /home/eldair/code/project/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#3 /home/eldair/code/project/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(109): tap()
#4 /home/eldair/code/project/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(28): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient()
#5 /home/eldair/code/project/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(32): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#6 /home/eldair/code/project/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(110): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect()
#7 /home/eldair/code/project/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(90): Illuminate\\Redis\\RedisManager->resolve()
#8 /home/eldair/code/project/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(258): Illuminate\\Redis\\RedisManager->connection()
#9 /home/eldair/code/project/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(62): Illuminate\\Cache\\RedisStore->connection()
#10 /home/eldair/code/project/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(97): Illuminate\\Cache\\RedisStore->get()
#11 /home/eldair/code/project/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(418): Illuminate\\Cache\\Repository->get()
#12 /home/eldair/code/project/vendor/laravel/telescope/src/Watchers/DumpWatcher.php(43): Illuminate\\Cache\\CacheManager->__call()
#13 /home/eldair/code/project/vendor/laravel/telescope/src/RegistersWatchers.php(48): Laravel\\Telescope\\Watchers\\DumpWatcher->register()
#14 /home/eldair/code/project/vendor/laravel/telescope/src/Telescope.php(141): Laravel\\Telescope\\Telescope::registerWatchers()
#15 /home/eldair/code/project/vendor/laravel/telescope/src/TelescopeServiceProvider.php(33): Laravel\\Telescope\\Telescope::start()
```

### Steps To Reproduce:

Enable dump watcher and open telescope

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
