### ISSUE TITLE
'Class "Redis" not found' errors logged when using Sail + Redis + Telescope.

### ISSUE THREAD

**Issue by Redtama** [laravel/telescope#1270]
- Telescope Version: 4.9.6
- Laravel Version: 9.39.0
- PHP Version: 8.1.12
- Database Driver & Version: MySQL 8.0.31

### Description:
With a fresh Laravel install using Sail and including a redis service and setting `CACHE_DRIVER` to `redis`, installing Telescope immediately results in the logs being flooded with `Class "Redis" not found` errors.

**Note:** Redis is working perfectly well alongside the `phpredis` PHP extension which is already included with Laravel Sail as stated in the documentation: 

> If you are using [Laravel Sail](https://laravel.com/docs/9.x/sail), this extension is already installed in your application's Docker container.
>  -- _https://laravel.com/docs/9.x/redis#introduction_

Any calls to `\Illuminate\Support\Facades\Redis::xxx` functions execute without issue in route handlers and even when executed in Tinker. The errors are only logged by Telescope itself.

I believe this may be related to: https://github.com/laravel/telescope/issues/1023

### Steps To Reproduce:
- Create a fresh project with `curl -s "https://laravel.build/example-app?with=mysql,redis" | bash`
- In `.env` set `CACHE_DRIVER` to `redis`
- Run `cd example-app && vendor/bin/sail up -d`
- Run `sail composer require laravel/telescope`
- Check your `storage/logs/laravel.log` file.

### Full Stacktrace
```
[2022-11-12 01:49:09] local.ERROR: Class "Redis" not found {"exception":"[object] (Error(code: 0): Class \"Redis\" not found at /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:81)
[stacktrace]
#0 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(34): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient(Array)
#1 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(38): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#2 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(112): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect(Array, Array)
#3 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(91): Illuminate\\Redis\\RedisManager->resolve('cache')
#4 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(258): Illuminate\\Redis\\RedisManager->connection('cache')
#5 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(62): Illuminate\\Cache\\RedisStore->connection()
#6 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(97): Illuminate\\Cache\\RedisStore->get('telescope:dump-...')
#7 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(418): Illuminate\\Cache\\Repository->get('telescope:dump-...')
#8 /Users/usr/Developer/example-app/vendor/laravel/telescope/src/Watchers/DumpWatcher.php(43): Illuminate\\Cache\\CacheManager->__call('get', Array)
#9 /Users/usr/Developer/example-app/vendor/laravel/telescope/src/RegistersWatchers.php(48): Laravel\\Telescope\\Watchers\\DumpWatcher->register(Object(Illuminate\\Foundation\\Application))
#10 /Users/usr/Developer/example-app/vendor/laravel/telescope/src/Telescope.php(141): Laravel\\Telescope\\Telescope::registerWatchers(Object(Illuminate\\Foundation\\Application))
#11 /Users/usr/Developer/example-app/vendor/laravel/telescope/src/TelescopeServiceProvider.php(33): Laravel\\Telescope\\Telescope::start(Object(Illuminate\\Foundation\\Application))
#12 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Telescope\\TelescopeServiceProvider->boot()
#13 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#15 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#16 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#17 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(933): Illuminate\\Container\\Container->call(Array)
#18 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(914): Illuminate\\Foundation\\Application->bootProvider(Object(Laravel\\Telescope\\TelescopeServiceProvider))
#19 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Laravel\\Telescope\\TelescopeServiceProvider), 16)
#20 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(915): array_walk(Array, Object(Closure))
#21 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#22 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#23 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(383): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#24 /Users/usr/Developer/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(153): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#25 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 {main}
"} 
```

**Comment by driesvints** [comment]
Please try the solution here: https://github.com/laravel/telescope/issues/1023#issuecomment-962663627

**Comment by satya-kr** [comment]
Add this line in  `TelescopeServiceProvider.php` 

```bash
public function register(): void
    {
     
        ...

        if ($this->app->environment('local') && $this->app->runningInConsole()) {
            config(['telescope.enabled' => false]);
        }

        ...
    }
