### ISSUE TITLE
Telescope tries to get primary key of Pivot model

### ISSUE THREAD

**Issue by Cellard** [laravel/telescope#1277]
- Telescope Version: 4.9.6
- Laravel Version: 9.42.2
- PHP Version: 8.1.12
- Database Driver & Version: MySQL 8.0.31 - Homebrew

### Description:

We have two models — `Game` and `Team` with pivot between. Pivot is keyless (table has composite primary key game_id+team_id), with some additional columns. Pivot drives using `GameTeamPivot` custom intermediate model.

First time (on empty table) I ran `sync`, all was ok. Next time, then `sync` detaches old records, application throws:

```
The attribute [id] either does not exist or was not retrieved for model [App\Models\Pivots\GameTeamPivot]. {"exception":"[object] (Illuminate\\Database\\Eloquent\\MissingAttributeException(code: 0): The attribute [id] either does not exist or was not retrieved for model [App\\Models\\Pivots\\GameTeamPivot]. at /Users/pm/www/fcz/press/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:474)
[stacktrace]
#0 /Users/pm/www/fcz/press/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(454): Illuminate\\Database\\Eloquent\\Model->throwMissingAttributeExceptionIfApplicable('id')
#1 /Users/pm/www/fcz/press/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1954): Illuminate\\Database\\Eloquent\\Model->getAttribute('id')
#2 /Users/pm/www/fcz/press/vendor/laravel/telescope/src/FormatModel.php(17): Illuminate\\Database\\Eloquent\\Model->getKey()
#3 /Users/pm/www/fcz/press/vendor/laravel/telescope/src/Watchers/ModelWatcher.php(54): Laravel\\Telescope\\FormatModel::given(Object(App\\Models\\Pivots\\GameTeamPivot))
#4 /Users/pm/www/fcz/press/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(418): Laravel\\Telescope\\Watchers\\ModelWatcher->recordAction('eloquent.update...', Array)
#5 /Users/pm/www/fcz/press/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('eloquent.update...', Array)
#6 /Users/pm/www/fcz/press/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(189): Illuminate\\Events\\Dispatcher->dispatch('eloquent.update...', Array)
#7 /Users/pm/www/fcz/press/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1210): Illuminate\\Database\\Eloquent\\Model->fireModelEvent('updated', false)
#8 /Users/pm/www/fcz/press/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1121): Illuminate\\Database\\Eloquent\\Model->performUpdate(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /Users/pm/www/fcz/press/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(245): Illuminate\\Database\\Eloquent\\Model->save()
#10 /Users/pm/www/fcz/press/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(209): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->updateExistingPivotUsingCustomClass(1, Array, false)
#11 /Users/pm/www/fcz/press/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(187): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->updateExistingPivot(1, Array, false)
#12 /Users/pm/www/fcz/press/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(114): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->attachNew(Array, Array, false)
#13 /Users/pm/www/fcz/press/app/Jobs/Offsite/GamesJob.php(105): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->sync(Array)
```

### Steps To Reproduce:

Make `Game` and `Team` models with only primary key in table.

Make `GameTeam` pivot:

```php
Schema::create('game_team', function (Blueprint $table) {
            $table->foreignIdFor(\App\Models\Game::class)
                ->constrained()
                ->cascadeOnDelete()
                ->cascadeOnUpdate();

            $table->foreignIdFor(\App\Models\Team::class)
                ->constrained()
                ->cascadeOnDelete()
                ->cascadeOnUpdate();

            $table->enum('side', ['home', 'guest']);
            $table->unsignedInteger('goals')->default(0);
            $table->json('players')->nullable();

            $table->primary(['game_id', 'team_id'], 'PRIMARY');
        });
```

Make Pivot model. Notice, that it casts `side` attribute with `enum` (maybe it is important...):

```php
class GameTeamPivot extends Pivot
{
    protected $casts = [
        'side' => GameSide::class,
        'players' => 'array'
    ];
}
```

Add relation to `Team` model:

```php
class Team extends Model 
{
    public function games(): BelongsToMany
    {
        return $this->belongsToMany(Game::class)
            ->using(GameTeamPivot::class)
            ->as('playing')
            ->withPivot('side', 'goals', 'players');
    }
}
```

Add relation to `Game` model:

```php
class Game extends Model
{
    public function teams(): BelongsToMany
    {
        return $this->belongsToMany(Team::class)
            ->using(GameTeamPivot::class)
            ->as('playing')
            ->withPivot('side', 'goals', 'players');
    }
}
```

Insert one `Game` and two `Team` in database. Then run such script twice:

```php
$game = Game::find(1);
$homeTeam = Team::find(1);
$guestTeam = Team::find(2);

$data = [
    $homeTeam->id => ['side' => GameSide::Home->value],
    $guestTeam->id => ['side' => GameSide::Guest->value],
];

$game->teams()->sync($data);
```

**Comment by driesvints** [comment]
Laravel does not support composite primary keys: https://laravel.com/docs/9.x/eloquent#composite-primary-keys
