### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by andrewminion-luminfire** [laravel/telescope#1353]
### Telescope Version

4.14.4

### Laravel Version

9.52.8

### PHP Version

8.1.11

### Description

As a result of https://github.com/laravel/telescope/pull/1349, I’m seeing `Exception: Serialization of 'Closure' is not allowed` errors in my app.

Context:

- The app uses redis queue workers and Horizon
- The exception occurs while the queue worker is processing a job

It seems that it’s due to the anonymous `fn()` [here](https://github.com/laravel/telescope/commit/9bbfc8f32fc26e2af85e1130ecde6a85859efa4d#diff-82c75df4b09d9a074291ebb138286af7e36da2156e8f2a9077218fc5f2e2dd97R671-R673), and it ultimately fails [here](https://github.com/laravel/framework/blob/c60191f33a88f91685634b157b4dc515381fccd1/src/Illuminate/Queue/Queue.php#L158)

### Steps To Reproduce

I haven’t yet nailed down exactly which job causes this

**Comment by andrewminion-luminfire** [comment]
It’s happening when a job is [processed](https://github.com/laravel/telescope/blob/08930adb80b77f67d561ac1b9bb5f6a7e80d8791/src/ListensForStorageOpportunities.php#L85-L87), [fails](https://github.com/laravel/telescope/blob/08930adb80b77f67d561ac1b9bb5f6a7e80d8791/src/ListensForStorageOpportunities.php#L89-L91), and when the app is [terminating](https://github.com/laravel/telescope/blob/08930adb80b77f67d561ac1b9bb5f6a7e80d8791/src/ListensForStorageOpportunities.php#L64-L66)

**Comment by andrewminion-luminfire** [comment]
@nunomaduro here you go; there are actually four distinct stack traces:

<details>
<summary>stacktrace 1</summary>

```
Exception Serialization of 'Closure' is not allowed
(unknown method)(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:158)
serialize(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:158)
Illuminate\Queue\Queue::createObjectPayload(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:127)
Illuminate\Queue\Queue::createPayloadArray(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php:212)
Illuminate\Queue\RedisQueue::createPayloadArray(/home/staging/example.com/vendor/laravel/horizon/src/RedisQueue.php:86)
Laravel\Horizon\RedisQueue::createPayloadArray(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:105)
Illuminate\Queue\Queue::createPayload(/home/staging/example.com/vendor/laravel/horizon/src/RedisQueue.php:104)
Laravel\Horizon\RedisQueue::later(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:250)
Illuminate\Bus\Dispatcher::pushCommandToQueue(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:229)
Illuminate\Bus\Dispatcher::dispatchToQueue(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:77)
Illuminate\Bus\Dispatcher::dispatch(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php:193)
Illuminate\Foundation\Bus\PendingDispatch::__destruct(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php:498)
Illuminate\Support\Collection::whenNotEmpty(/home/staging/example.com/vendor/laravel/telescope/src/Telescope.php:673)
Laravel\Telescope\Telescope::Laravel\Telescope\{closure}()
call_user_func(/home/staging/example.com/vendor/laravel/telescope/src/Telescope.php:293)
Laravel\Telescope\Telescope::withoutRecording(/home/staging/example.com/vendor/laravel/telescope/src/Telescope.php:683)
Laravel\Telescope\Telescope::store(/home/staging/example.com/vendor/laravel/telescope/src/ListensForStorageOpportunities.php:110)
Laravel\Telescope\Telescope::storeIfDoneProcessingJob(/home/staging/example.com/vendor/laravel/telescope/src/ListensForStorageOpportunities.php:86)
Laravel\Telescope\Telescope::Laravel\Telescope\{closure}(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:421)
Illuminate\Events\Dispatcher::Illuminate\Events\{closure}(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:249)
Illuminate\Events\Dispatcher::dispatch(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:628)
Illuminate\Queue\Worker::raiseAfterJobEvent(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:427)
Illuminate\Queue\Worker::process(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:375)
Illuminate\Queue\Worker::runJob(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:173)
Illuminate\Queue\Worker::daemon(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:148)
Illuminate\Queue\Console\WorkCommand::runWorker(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:131)
Illuminate\Queue\Console\WorkCommand::handle(/home/staging/example.com/vendor/laravel/horizon/src/Console/WorkCommand.php:51)
Laravel\Horizon\Console\WorkCommand::handle(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36)
Illuminate\Container\BoundMethod::Illuminate\Container\{closure}(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/Util.php:41)
Illuminate\Container\Util::unwrapIfClosure(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93)
Illuminate\Container\BoundMethod::callBoundMethod(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37)
Illuminate\Container\BoundMethod::call(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:661)
Illuminate\Container\Container::call(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Console/Command.php:183)
Illuminate\Console\Command::execute(/home/staging/example.com/vendor/symfony/console/Command/Command.php:326)
Symfony\Component\Console\Command\Command::run(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Console/Command.php:153)
Illuminate\Console\Command::run(/home/staging/example.com/vendor/symfony/console/Application.php:1063)
Symfony\Component\Console\Application::doRunCommand(/home/staging/example.com/vendor/symfony/console/Application.php:320)
Symfony\Component\Console\Application::doRun(/home/staging/example.com/vendor/symfony/console/Application.php:174)
Symfony\Component\Console\Application::run(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Console/Application.php:102)
Illuminate\Console\Application::run(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:155)
Illuminate\Foundation\Console\Kernel::handle(/home/staging/example.com/artisan:37)
```
</details>

<details>
<summary>stacktrace 2</summary>

```
Exception Serialization of 'Closure' is not allowed
(unknown method)(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:158)
serialize(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:158)
Illuminate\Queue\Queue::createObjectPayload(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:127)
Illuminate\Queue\Queue::createPayloadArray(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php:212)
Illuminate\Queue\RedisQueue::createPayloadArray(/home/staging/example.com/vendor/laravel/horizon/src/RedisQueue.php:86)
Laravel\Horizon\RedisQueue::createPayloadArray(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:105)
Illuminate\Queue\Queue::createPayload(/home/staging/example.com/vendor/laravel/horizon/src/RedisQueue.php:104)
Laravel\Horizon\RedisQueue::later(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:250)
Illuminate\Bus\Dispatcher::pushCommandToQueue(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:229)
Illuminate\Bus\Dispatcher::dispatchToQueue(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:77)
Illuminate\Bus\Dispatcher::dispatch(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php:193)
Illuminate\Foundation\Bus\PendingDispatch::__destruct(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php:498)
Illuminate\Support\Collection::whenNotEmpty(/home/staging/example.com/vendor/laravel/telescope/src/Telescope.php:673)
Laravel\Telescope\Telescope::Laravel\Telescope\{closure}()
call_user_func(/home/staging/example.com/vendor/laravel/telescope/src/Telescope.php:293)
Laravel\Telescope\Telescope::withoutRecording(/home/staging/example.com/vendor/laravel/telescope/src/Telescope.php:683)
Laravel\Telescope\Telescope::store(/home/staging/example.com/vendor/laravel/telescope/src/ListensForStorageOpportunities.php:110)
Laravel\Telescope\Telescope::storeIfDoneProcessingJob(/home/staging/example.com/vendor/laravel/telescope/src/ListensForStorageOpportunities.php:90)
Laravel\Telescope\Telescope::Laravel\Telescope\{closure}(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:421)
Illuminate\Events\Dispatcher::Illuminate\Events\{closure}(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:249)
Illuminate\Events\Dispatcher::dispatch(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:195)
Illuminate\Queue\Jobs\Job::fail(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:582)
Illuminate\Queue\Worker::failJob(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:528)
Illuminate\Queue\Worker::markJobAsFailedIfWillExceedMaxAttempts(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:452)
Illuminate\Queue\Worker::handleJobException(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:429)
Illuminate\Queue\Worker::process(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:375)
Illuminate\Queue\Worker::runJob(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:173)
Illuminate\Queue\Worker::daemon(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:148)
Illuminate\Queue\Console\WorkCommand::runWorker(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:131)
Illuminate\Queue\Console\WorkCommand::handle(/home/staging/example.com/vendor/laravel/horizon/src/Console/WorkCommand.php:51)
Laravel\Horizon\Console\WorkCommand::handle(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36)
Illuminate\Container\BoundMethod::Illuminate\Container\{closure}(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/Util.php:41)
Illuminate\Container\Util::unwrapIfClosure(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93)
Illuminate\Container\BoundMethod::callBoundMethod(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37)
Illuminate\Container\BoundMethod::call(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:661)
Illuminate\Container\Container::call(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Console/Command.php:183)
Illuminate\Console\Command::execute(/home/staging/example.com/vendor/symfony/console/Command/Command.php:326)
Symfony\Component\Console\Command\Command::run(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Console/Command.php:153)
Illuminate\Console\Command::run(/home/staging/example.com/vendor/symfony/console/Application.php:1063)
Symfony\Component\Console\Application::doRunCommand(/home/staging/example.com/vendor/symfony/console/Application.php:320)
Symfony\Component\Console\Application::doRun(/home/staging/example.com/vendor/symfony/console/Application.php:174)
Symfony\Component\Console\Application::run(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Console/Application.php:102)
Illuminate\Console\Application::run(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:155)
Illuminate\Foundation\Console\Kernel::handle(/home/staging/example.com/artisan:37)
```
</details>

<details>
<summary>stacktrace 3</summary>

```
Exception Serialization of 'Closure' is not allowed
(unknown method)(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:158)
serialize(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:158)
Illuminate\Queue\Queue::createObjectPayload(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:127)
Illuminate\Queue\Queue::createPayloadArray(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php:212)
Illuminate\Queue\RedisQueue::createPayloadArray(/home/staging/example.com/vendor/laravel/horizon/src/RedisQueue.php:86)
Laravel\Horizon\RedisQueue::createPayloadArray(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:105)
Illuminate\Queue\Queue::createPayload(/home/staging/example.com/vendor/laravel/horizon/src/RedisQueue.php:104)
Laravel\Horizon\RedisQueue::later(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:250)
Illuminate\Bus\Dispatcher::pushCommandToQueue(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:229)
Illuminate\Bus\Dispatcher::dispatchToQueue(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:77)
Illuminate\Bus\Dispatcher::dispatch(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php:193)
Illuminate\Foundation\Bus\PendingDispatch::__destruct(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php:498)
Illuminate\Support\Collection::whenNotEmpty(/home/staging/example.com/vendor/laravel/telescope/src/Telescope.php:673)
Laravel\Telescope\Telescope::Laravel\Telescope\{closure}()
call_user_func(/home/staging/example.com/vendor/laravel/telescope/src/Telescope.php:293)
Laravel\Telescope\Telescope::withoutRecording(/home/staging/example.com/vendor/laravel/telescope/src/Telescope.php:683)
Laravel\Telescope\Telescope::store(/home/staging/example.com/vendor/laravel/telescope/src/ListensForStorageOpportunities.php:65)
Laravel\Telescope\Telescope::Laravel\Telescope\{closure}(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36)
Illuminate\Container\BoundMethod::Illuminate\Container\{closure}(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/Util.php:41)
Illuminate\Container\Util::unwrapIfClosure(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:81)
Illuminate\Container\BoundMethod::callBoundMethod(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37)
Illuminate\Container\BoundMethod::call(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:661)
Illuminate\Container\Container::call(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1173)
Illuminate\Foundation\Application::terminate(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:174)
Illuminate\Foundation\Console\Kernel::terminate(/home/staging/example.com/artisan:51)
```
</details>

<details>
<summary>stacktrace 4</summary>

```
Exception Serialization of 'Closure' is not allowed
(unknown method)(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:158)
serialize(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:158)
Illuminate\Queue\Queue::createObjectPayload(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:127)
Illuminate\Queue\Queue::createPayloadArray(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php:212)
Illuminate\Queue\RedisQueue::createPayloadArray(/home/staging/example.com/vendor/laravel/horizon/src/RedisQueue.php:86)
Laravel\Horizon\RedisQueue::createPayloadArray(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:105)
Illuminate\Queue\Queue::createPayload(/home/staging/example.com/vendor/laravel/horizon/src/RedisQueue.php:104)
Laravel\Horizon\RedisQueue::later(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:250)
Illuminate\Bus\Dispatcher::pushCommandToQueue(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:229)
Illuminate\Bus\Dispatcher::dispatchToQueue(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:77)
Illuminate\Bus\Dispatcher::dispatch(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php:193)
Illuminate\Foundation\Bus\PendingDispatch::__destruct(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php:498)
Illuminate\Support\Collection::whenNotEmpty(/home/staging/example.com/vendor/laravel/telescope/src/Telescope.php:673)
Laravel\Telescope\Telescope::Laravel\Telescope\{closure}()
call_user_func(/home/staging/example.com/vendor/laravel/telescope/src/Telescope.php:293)
Laravel\Telescope\Telescope::withoutRecording(/home/staging/example.com/vendor/laravel/telescope/src/Telescope.php:683)
Laravel\Telescope\Telescope::store(/home/staging/example.com/vendor/laravel/telescope/src/ListensForStorageOpportunities.php:110)
Laravel\Telescope\Telescope::storeIfDoneProcessingJob(/home/staging/example.com/vendor/laravel/telescope/src/ListensForStorageOpportunities.php:90)
Laravel\Telescope\Telescope::Laravel\Telescope\{closure}(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:421)
Illuminate\Events\Dispatcher::Illuminate\Events\{closure}(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:249)
Illuminate\Events\Dispatcher::dispatch(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:195)
Illuminate\Queue\Jobs\Job::fail(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:582)
Illuminate\Queue\Worker::failJob(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:505)
Illuminate\Queue\Worker::markJobAsFailedIfAlreadyExceedsMaxAttempts(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:415)
Illuminate\Queue\Worker::process(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:375)
Illuminate\Queue\Worker::runJob(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:173)
Illuminate\Queue\Worker::daemon(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:148)
Illuminate\Queue\Console\WorkCommand::runWorker(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:131)
Illuminate\Queue\Console\WorkCommand::handle(/home/staging/example.com/vendor/laravel/horizon/src/Console/WorkCommand.php:51)
Laravel\Horizon\Console\WorkCommand::handle(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36)
Illuminate\Container\BoundMethod::Illuminate\Container\{closure}(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/Util.php:41)
Illuminate\Container\Util::unwrapIfClosure(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93)
Illuminate\Container\BoundMethod::callBoundMethod(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37)
Illuminate\Container\BoundMethod::call(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:661)
Illuminate\Container\Container::call(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Console/Command.php:183)
Illuminate\Console\Command::execute(/home/staging/example.com/vendor/symfony/console/Command/Command.php:326)
Symfony\Component\Console\Command\Command::run(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Console/Command.php:153)
Illuminate\Console\Command::run(/home/staging/example.com/vendor/symfony/console/Application.php:1063)
Symfony\Component\Console\Application::doRunCommand(/home/staging/example.com/vendor/symfony/console/Application.php:320)
Symfony\Component\Console\Application::doRun(/home/staging/example.com/vendor/symfony/console/Application.php:174)
Symfony\Component\Console\Application::run(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Console/Application.php:102)
Illuminate\Console\Application::run(/home/staging/example.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:155)
Illuminate\Foundation\Console\Kernel::handle(/home/staging/example.com/artisan:37)
```
</details>

**Comment by andrewminion-luminfire** [comment]
@nunomaduro those are copied from rollbar; I just updated the server to log to a file so we can get a more typical stacktrace:

```
[2023-06-02 16:16:05] staging.ERROR: Serialization of 'Closure' is not allowed {"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed at /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:158)
[stacktrace]
#0 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(158): serialize(Object(Laravel\\Telescope\\Jobs\\ProcessPendingUpdates))
#1 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(127): Illuminate\\Queue\\Queue->createObjectPayload(Object(Laravel\\Telescope\\Jobs\\ProcessPendingUpdates), NULL)
#2 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(212): Illuminate\\Queue\\Queue->createPayloadArray(Object(Laravel\\Telescope\\Jobs\\ProcessPendingUpdates), NULL, '')
#3 /home/staging/example.com/vendor/laravel/horizon/src/RedisQueue.php(86): Illuminate\\Queue\\RedisQueue->createPayloadArray(Object(Laravel\\Telescope\\Jobs\\ProcessPendingUpdates), NULL, '')
#4 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(105): Laravel\\Horizon\\RedisQueue->createPayloadArray(Object(Laravel\\Telescope\\Jobs\\ProcessPendingUpdates), NULL, '')
#5 /home/staging/example.com/vendor/laravel/horizon/src/RedisQueue.php(104): Illuminate\\Queue\\Queue->createPayload(Object(Laravel\\Telescope\\Jobs\\ProcessPendingUpdates), NULL, '')
#6 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(250): Laravel\\Horizon\\RedisQueue->later(Object(Illuminate\\Support\\Carbon), Object(Laravel\\Telescope\\Jobs\\ProcessPendingUpdates))
#7 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(229): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Laravel\\Horizon\\RedisQueue), Object(Laravel\\Telescope\\Jobs\\ProcessPendingUpdates))
#8 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(Laravel\\Telescope\\Jobs\\ProcessPendingUpdates))
#9 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(193): Illuminate\\Bus\\Dispatcher->dispatch(Object(Laravel\\Telescope\\Jobs\\ProcessPendingUpdates))
#10 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(498): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#11 /home/staging/example.com/vendor/laravel/telescope/src/Telescope.php(673): Illuminate\\Support\\Collection->whenNotEmpty(Object(Closure))
#12 [internal function]: Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#13 /home/staging/example.com/vendor/laravel/telescope/src/Telescope.php(293): call_user_func(Object(Closure))
#14 /home/staging/example.com/vendor/laravel/telescope/src/Telescope.php(683): Laravel\\Telescope\\Telescope::withoutRecording(Object(Closure))
#15 /home/staging/example.com/vendor/laravel/telescope/src/ListensForStorageOpportunities.php(110): Laravel\\Telescope\\Telescope::store(Object(Laravel\\Telescope\\Storage\\DatabaseEntriesRepository))
#16 /home/staging/example.com/vendor/laravel/telescope/src/ListensForStorageOpportunities.php(86): Laravel\\Telescope\\Telescope::storeIfDoneProcessingJob(Object(Illuminate\\Queue\\Events\\JobProcessed), Object(Illuminate\\Foundation\\Application))
#17 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}(Object(Illuminate\\Queue\\Events\\JobProcessed))
#18 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('...', Array)
#19 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(628): Illuminate\\Events\\Dispatcher->dispatch('...')
#20 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(427): Illuminate\\Queue\\Worker->raiseAfterJobEvent('...', Object(Illuminate\\Queue\\Jobs\\RedisJob))
#21 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->process('...', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#22 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), '...', Object(Illuminate\\Queue\\WorkerOptions))
#23 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(148): Illuminate\\Queue\\Worker->daemon('...', '...', Object(Illuminate\\Queue\\WorkerOptions))
#24 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(131): Illuminate\\Queue\\Console\\WorkCommand->runWorker('...', '...')
#25 /home/staging/example.com/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
#26 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#27 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#28 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#29 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#30 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#31 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#32 /home/staging/example.com/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#33 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(153): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#34 /home/staging/example.com/vendor/symfony/console/Application.php(1063): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 /home/staging/example.com/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 /home/staging/example.com/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 /home/staging/example.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#39 /home/staging/example.com/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 {main}
"}
```

**Comment by andrewminion-luminfire** [comment]
@nunomaduro I just tested #1354 in my app and it appears to have solved the issue; thanks so much!!

**Comment by nunomaduro** [comment]
This is fixed on the latest version.
