### ISSUE TITLE
ErrorException: Array to string conversion

### ISSUE THREAD

**Issue by tillkruss** [laravel/telescope#174]
When running `php artisan horizon` we encounter this error:

```
ErrorException: Array to string conversion
#32 vendor/laravel/telescope/src/Watchers/RedisWatcher.php(46): handleError
#31 vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): handleError
#30 vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(0): implode
#29 vendor/laravel/telescope/src/Watchers/RedisWatcher.php(46): formatCommand
#28 vendor/laravel/telescope/src/Watchers/RedisWatcher.php(32): recordCommand
#27 vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Illuminate\Events\{closure}
#26 vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): dispatch
#25 vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(134): event
#24 vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(119): command
#23 vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(347): eval
#22 vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(205): migrateExpiredJobs
#21 vendor/laravel/horizon/src/RedisQueue.php(108): migrateExpiredJobs
#20 vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(188): migrate
#19 vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(164): pop
#18 vendor/laravel/horizon/src/RedisQueue.php(92): pop
#17 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(247): getNextJob
#16 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(107): daemon
#15 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): runWorker
#14 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): handle
#13 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(0): call_user_func_array
#12 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): Illuminate\Container\{closure}
#11 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): callBoundMethod
#10 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): call
#9 vendor/laravel/framework/src/Illuminate/Container/Container.php(572): call
#8 vendor/laravel/framework/src/Illuminate/Console/Command.php(183): execute
#7 vendor/symfony/console/Command/Command.php(255): run
#6 vendor/laravel/framework/src/Illuminate/Console/Command.php(170): run
#5 vendor/symfony/console/Application.php(886): doRunCommand
#4 vendor/symfony/console/Application.php(262): doRun
#3 vendor/symfony/console/Application.php(145): run
#2 vendor/laravel/framework/src/Illuminate/Console/Application.php(89): run
#1 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): handle
#0 artisan(37): null
```

**Comment by browner12** [comment]
you could add an array wrap here?

https://github.com/laravel/telescope/blob/1.0/src/Watchers/RedisWatcher.php#L46

**Comment by themsaid** [comment]
I can't replicate this, can you investigate it on your end?

**Comment by tillkruss** [comment]
I can't debug the code, because it's in production and I have no way to editing files there.

It can't be the command, that has to to be a `string`, otherwise it wouldn't be called in `Connection::command()`.

My best guess would be this PhpRedis' weird arguments:

https://github.com/laravel/framework/blob/6e3d568757a8e4124b49bf9ac94f1db7a66437a1/src/Illuminate/Redis/Connections/PhpRedisConnection.php#L76-L83

This confirms my suspicion:

```php
implode(' ', ['foo', ['bar', 'baz']]) // PHP Notice:  Array to string conversion
```

I'll submit a PR.

**Comment by Miljan9602** [comment]
When using telescope to log every redis request, it get this error if we are using sorted set zrangebyscore command with the limit option. This is how i call it.

Redis::zrangebyscore($key, 0, $fromTime, [
            'limit' => [
                'offset' => 0,
                'count' => $count
            ]
        ]);

This is your method:

/**
     * Format the given Redis command.
     *
     * @param  string  $command
     * @param  array  $parameters
     * @return string
     */
    private function formatCommand($command, $parameters)
    {
        $parameters = collect($parameters)->map(function ($parameter) {
            if (is_array($parameter)) {
                return collect($parameter)->map(function ($value, $key) {
                    return is_int($key) ? $value : "{$key} {$value}";
                })->implode(' ');
            }

            return $parameter;
        })->implode(' ');

        return "{$command} {$parameters}";
    }

Which want to return string, but it returns array. Because of this:  
           [
                'offset' => 0,
                'count' => $count
            ]
It tries to return 0 5.

Our parameter has value: 

$parameter = [▼
  "limit" => array:2 [▼
    0 => 0
    1 => 5
  ]
]

If we do: 

return collect($parameter)->map(function ($value, $key) {
                    return is_int($key) ? $value : "{$key} {$value}";
                })->implode(' ');

$key will have value "limit", where  is_int($key) will return false, and we will try to do this code "{$key} {$value}" which returns  Array to string conversion exceptionl, because our value is 
[▼
  0 => 0
  1 => 5
]

**Comment by swumao** [comment]
I have the same question.

When I use redis like this.. 
```php
Redis::connection()->command('ZREVRANGEBYSCORE', [
            'test', //,
            time(),
            '-inf',
            [
                'limit' => [
                    'offset' => 0,
                    'count'  => $count,
                ],
            ],
        ]);
```
An "Array to string conversion" ErrorException was throwed in ./vendor/laravel/telescope/src/Watchers/RedisWatcher.php:59

**Comment by vishalsirka** [comment]
ErrorException
Array to string conversion

i also getting this error.
