### ISSUE TITLE
Class setQueue does not exist on disabling filter

### ISSUE THREAD

**Issue by fridzema** [laravel/telescope#190]
I was stubborn to install telescope on my production server, everything goes well until i get al those mysql lock errors #180. I decided to disable the capturing for now on production like this (not the best check tough):
```php
if ($this->app->environment() != 'production') {
    return true;
}
```
After this update i receive multiple `Class setQueue does not exist` errors. 
After enabling again for production everything goes well.

Full stack trace:
```
ReflectionException: Class setQueue does not exist
#73 vendor/laravel/framework/src/Illuminate/Container/Container.php(779): __construct
#72 vendor/laravel/framework/src/Illuminate/Container/Container.php(779): build
#71 vendor/laravel/framework/src/Illuminate/Container/Container.php(658): resolve
#70 vendor/laravel/framework/src/Illuminate/Container/Container.php(609): make
#69 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(733): make
#68 vendor/laravel/framework/src/Illuminate/Container/Container.php(1222): offsetGet
#67 vendor/laravel/framework/src/Illuminate/Mail/MailServiceProvider.php(52): Illuminate\Mail\{closure}
#66 vendor/laravel/framework/src/Illuminate/Container/Container.php(776): build
#65 vendor/laravel/framework/src/Illuminate/Container/Container.php(658): resolve
#64 vendor/laravel/framework/src/Illuminate/Container/Container.php(609): make
#63 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(733): make
#62 vendor/laravel/framework/src/Illuminate/Container/Container.php(1222): offsetGet
#61 vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(161): resolveFacadeInstance
#60 vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(130): getFacadeRoot
#59 vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): __callStatic
#58 app/Http/Controllers/ApprovalController.php(156): sendUserApprovalConfirmationEmail
#57 app/Http/Controllers/ApprovalController.php(430): handleApproval
#56 app/Http/Controllers/ApprovalController.php(0): call_user_func_array
#55 vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): callAction
#54 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): dispatch
#53 vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): runController
#52 vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): run
#51 vendor/laravel/framework/src/Illuminate/Routing/Router.php(679): Illuminate\Routing\{closure}
#50 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\{closure}
#49 app/Http/Middleware/LogLastUserActivity.php(49): handle
#48 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#47 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#46 vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): handle
#45 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#44 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#43 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): handle
#42 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#41 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#40 vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): handle
#39 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#38 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#37 vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): handle
#36 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#35 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#34 vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): handle
#33 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#32 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#31 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): handle
#30 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#29 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#28 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): handle
#27 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#26 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#25 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): handle
#24 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#23 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#22 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): then
#21 vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): runRouteWithinStack
#20 vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): runRoute
#19 vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): dispatchToRoute
#18 vendor/laravel/framework/src/Illuminate/Routing/Router.php(611): dispatch
#17 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Http\{closure}
#16 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\{closure}
#15 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): handle
#14 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#13 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#12 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): handle
#11 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#10 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#9 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): handle
#8 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#7 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#6 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): handle
#5 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#4 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#3 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): then
#2 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): sendRequestThroughRouter
#1 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): handle
#0 public/index.php(53): null
```

**Comment by themsaid** [comment]
There's no sign of telescope in the stack trace, seems to be coming from your app.

**Comment by sebastiaanluca** [comment]
Same issue here since today. Only change was that I just updated to the latest Telescope version (0.1.8 from 0.1.6).

Yet I'm not sure if it's even related to Telescope. I've disabled [Clockwork](https://github.com/itsgoingd/clockwork) and it seems to prevent the error from being thrown. No idea what's causing this.

**Comment by themsaid** [comment]
That doesn't seem to be related to Telescope as I said earlier, so I have to close this issue for now.

Please open a new issue in case someone figured something wrong with Telescope.

**Comment by more-yogesh** [comment]
For MacBook Users just use command "valet restart", In my case its working now.
