### ISSUE TITLE
SQLSTATE[HY000] [1049] Unknown database 'xxxxxx' (SQL: select `tag` from `telescope_monitoring`)

### ISSUE THREAD

**Issue by mikebronner** [laravel/telescope#22]
Hi Taylor,

Thanks for sharing the beta. I just installed it and got the following stack-trace when trying to run `php artisan migrate` after running `php artisan telescope:install`. Please let me know if there is any additional information that would help.
```
[2018-10-23 15:14:19] development.ERROR: SQLSTATE[HY000] [1049] Unknown database 'portal' (SQL: select `tag` from `telescope_monitoring`) {"userId":1,"email":"mike@genealabs.com","exception":"[object] (Illuminate\\Database\\QueryException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'portal' (SQL: select `tag` from `telescope_monitoring`) at /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'portal' at /home/vagrant/Sites/portal.genealabs.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:50, PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'portal' at /home/vagrant/Sites/portal.genealabs.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:46)
[stacktrace]
#0 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select `tag` fr...', Array, Object(Closure))
#1 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select `tag` fr...', Array, Object(Closure))
#2 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2027): Illuminate\\Database\\Connection->select('select `tag` fr...', Array, true)
#3 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2219): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2499): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2221): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(248): Illuminate\\Database\\Query\\Builder->pluck('tag')
#7 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(235): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->monitoring()
#8 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/telescope/src/IncomingEntry.php(164): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->isMonitoring(Array)
#9 /home/vagrant/Sites/portal.genealabs.com/app/Providers/TelescopeServiceProvider.php(31): Laravel\\Telescope\\IncomingEntry->hasMonitoredTag()
#10 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): App\\Providers\\TelescopeServiceProvider->App\\Providers\\{closure}(Object(Laravel\\Telescope\\IncomingEntry))
#11 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): Closure->__invoke(Object(Laravel\\Telescope\\IncomingEntry))
#12 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(442): Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(Closure), 0)
#13 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->every(Object(Closure))
#14 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/telescope/src/Telescope.php(204): Illuminate\\Support\\HigherOrderCollectionProxy->__call('__invoke', Array)
#15 [internal function]: Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#16 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/telescope/src/Telescope.php(177): call_user_func(Object(Closure))
#17 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/telescope/src/Telescope.php(207): Laravel\\Telescope\\Telescope::withoutRecording(Object(Closure))
#18 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/telescope/src/Telescope.php(231): Laravel\\Telescope\\Telescope::record('cache', Object(Laravel\\Telescope\\IncomingEntry))
#19 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/telescope/src/Watchers/CacheWatcher.php(101): Laravel\\Telescope\\Telescope::recordCache(Object(Laravel\\Telescope\\IncomingEntry))
#20 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Laravel\\Telescope\\Watchers\\CacheWatcher->recordKeyForgotten(Object(Illuminate\\Cache\\Events\\KeyForgotten))
#21 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Cach...', Array)
#22 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(486): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Cach...')
#23 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(378): Illuminate\\Cache\\Repository->event(Object(Illuminate\\Cache\\Events\\KeyForgotten))
#24 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1027): Illuminate\\Cache\\Repository->Illuminate\\Cache\\{closure}(false)
#25 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(379): tap(false, Object(Closure))
#26 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Cache/RateLimiter.php(93): Illuminate\\Cache\\Repository->forget('mike@genealabs....')
#27 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Cache/RateLimiter.php(118): Illuminate\\Cache\\RateLimiter->resetAttempts('mike@genealabs....')
#28 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Foundation/Auth/ThrottlesLogins.php(67): Illuminate\\Cache\\RateLimiter->clear('mike@genealabs....')
#29 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php(104): App\\Http\\Controllers\\Auth\\LoginController->clearLoginAttempts(Object(Illuminate\\Http\\Request))
#30 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php(45): App\\Http\\Controllers\\Auth\\LoginController->sendLoginResponse(Object(Illuminate\\Http\\Request))
#31 [internal function]: App\\Http\\Controllers\\Auth\\LoginController->login(Object(Illuminate\\Http\\Request))
#32 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#33 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('login', Array)
#34 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Auth\\LoginController), 'login')
#35 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#36 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(679): Illuminate\\Routing\\Route->run()
#37 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/vagrant/Sites/portal.genealabs.com/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\RedirectIfAuthenticated->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#61 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#62 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#63 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(611): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#64 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#65 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#66 /home/vagrant/Sites/portal.genealabs.com/vendor/genealabs/laravel-casts/src/Http/Middleware/AssetInjection.php(10): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): GeneaLabs\\LaravelCasts\\Http\\Middleware\\AssetInjection->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /home/vagrant/Sites/portal.genealabs.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#70 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#73 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#76 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#79 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#82 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#85 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#86 /home/vagrant/Sites/portal.genealabs.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#87 /home/vagrant/Sites/portal.genealabs.com/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#88 {main}
"} 
```

**Comment by Diddyy** [comment]
I have this issue as well as none of the resources being made when telescope is installed. Such as the config file. Can not see any config/telescope.php has been made

**Comment by Diddyy** [comment]
After a fresh install of telescope I currently get the following when trying to migrate database.
```Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `created_at` datetime null) default character set utf8mb4 collate' at line 1")
      /Users/josh/code/hostinhub/vendor/laravel/framework/src/Illuminate/Database/Connection.php:452

  2   PDO::prepare("create table `telescope_entries` (`sequence` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `batch_id` char(36) not null, `family_hash` varchar(255) null, `should_display_on_index` tinyint(1) not null default '1', `type` varchar(20) not null, `content` json not null, `created_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'")
      /Users/josh/code/hostinhub/vendor/laravel/framework/src/Illuminate/Database/Connection.php:452

  Please use the argument -v to see more details.```

**Comment by themsaid** [comment]
@Diddyy please open a new issue, it's completely different.
