### ISSUE TITLE
Cannot cache config with telescope installed and custom session driver

### ISSUE THREAD

**Issue by CiiDyR** [laravel/telescope#279]
It seems like there is a problem with telescope and custom session drivers.
If telescope is installed while wanting to `artisan config:cache`, the following error will be thrown:

> In Manager.php line 99:
>                                         
>   Driver [app.database] not supported.  

app.database obviously being my custom session driver.
If I configure the Session Driver to be database, it will cache without issue.

My DatabaseSessionHandler only overrides one method of Illuminate\Session\DatabaseSessionHandler, and that is addUserInformation.

I don't really see why that is.
If more information is needed, I am happy to provide it.

**Comment by themsaid** [comment]
How do I replicate this issue?

**Comment by CiiDyR** [comment]
I was able to reproduce it in a new project with the following steps:

0. laravel new test && cd test && composer require laravel/telescope --dev && php artisan telescope:install

1. Create SessionServiceProvider.php in app/Providers:
https://gist.github.com/CiiDyR/1bd49aa33aef1dd04d6a2003efffae6a

2. Create DatabaseSessionHandler.php in app/Sessions:
https://gist.github.com/CiiDyR/41d18ed0f0d03f43cb6aca1bfeed767b

3. Register the `App\Providers\SessionServiceProvider` in `config/app.php`

4. In `.env` change SESSION_DRIVER to `app.database`, the newly created one.

5. Now just run `artisan config:cache`, you will get the error I am getting.

You don't even need to create the sessions table, or even modify it to fit the goal of the SessionHandler.
Neither is it required to even have a database connection setup.

I hope you are able to reproduce it now.

**Comment by themsaid** [comment]
If anyone else is facing the same issue in their app please let me, I can't replicate the issue on a fresh laravel installation.

**Comment by CiiDyR** [comment]
I just tested it on another machine.
It's the same there.

I made a repository for you to check it out.
https://github.com/CiiDyR/telescope-session-issue

I did only the steps I described above.

**Comment by themsaid** [comment]
Please share the full stack trace of the error then so we can help.

**Comment by CiiDyR** [comment]
This is what's logged. The error is resolved as soon as I remove telescope with composer.
And instantly returns whenever re-require it.

This is what led me to believe it must be somehow caused by telescope.


```
[2018-11-02 16:09:41] local.ERROR: Driver [app.database] not supported. {"exception":"[object] (InvalidArgumentException(code: 0): Driver [app.database] not supported. at /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Support/Manager.php:99)
[stacktrace]
#0 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Support/Manager.php(71): Illuminate\\Support\\Manager->createDriver('app.database')
#1 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Session/SessionServiceProvider.php(47): Illuminate\\Support\\Manager->driver()
#2 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): Illuminate\\Session\\SessionServiceProvider->Illuminate\\Session\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#3 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\\Container\\Container->build(Object(Closure))
#4 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\\Container\\Container->resolve('session.store', Array)
#5 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(733): Illuminate\\Container\\Container->make('session.store', Array)
#6 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(1222): Illuminate\\Foundation\\Application->make('session.store')
#7 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(123): Illuminate\\Container\\Container->offsetGet('session.store')
#8 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(94): Illuminate\\Auth\\AuthManager->createSessionDriver('web', Array)
#9 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(68): Illuminate\\Auth\\AuthManager->resolve('web')
#10 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(292): Illuminate\\Auth\\AuthManager->guard()
#11 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Illuminate\\Auth\\AuthManager->__call('hasUser', Array)
#12 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/telescope/src/Telescope.php(201): Illuminate\\Support\\Facades\\Facade::__callStatic('hasUser', Array)
#13 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/telescope/src/Telescope.php(277): Laravel\\Telescope\\Telescope::record('exception', Object(Laravel\\Telescope\\IncomingExceptionEntry))
#14 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/telescope/src/Watchers/ExceptionWatcher.php(46): Laravel\\Telescope\\Telescope::recordException(Object(Laravel\\Telescope\\IncomingExceptionEntry))
#15 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Laravel\\Telescope\\Watchers\\ExceptionWatcher->recordException(Object(Illuminate\\Log\\Events\\MessageLogged))
#16 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Log\\\\...', Array)
#17 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Log/Logger.php(210): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Log\\\\...')
#18 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Log/Logger.php(174): Illuminate\\Log\\Logger->fireLogEvent('error', 'Driver [app.dat...', Array)
#19 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Log/Logger.php(87): Illuminate\\Log\\Logger->writeLog('error', 'Driver [app.dat...', Array)
#20 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(488): Illuminate\\Log\\Logger->error('Driver [app.dat...', Array)
#21 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(114): Illuminate\\Log\\LogManager->error('Driver [app.dat...', Array)
#22 /home/ciidyr/projects/playgrounds/laravel-telescope-test/app/Exceptions/Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(InvalidArgumentException))
#23 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(60): App\\Exceptions\\Handler->report(Object(InvalidArgumentException))
#24 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(353): NunoMaduro\\Collision\\Adapters\\Laravel\\ExceptionHandler->report(Object(InvalidArgumentException))
#25 /home/ciidyr/projects/playgrounds/laravel-telescope-test/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(124): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(InvalidArgumentException))
#26 /home/ciidyr/projects/playgrounds/laravel-telescope-test/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 {main}
"}

```

**Comment by themsaid** [comment]
Please install the latest release and try again.
