### ISSUE TITLE
Method Illuminate\Auth\RequestGuard::getUser does not exist.

### ISSUE THREAD

**Issue by Mattnmoore** [laravel/telescope#317]
Seems to be related to #277, I'm getting the following error:
```
Method Illuminate\Auth\RequestGuard::getUser does not exist.
```
And the [interface](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Contracts/Auth/Guard.php) doesn't seem to have that method defined.

**Comment by themsaid** [comment]
Telescope doesn't use `getUser()` anywhere! Please share the complete stack trace.

**Comment by Mattnmoore** [comment]
```
0: "#0 /vagrant/api/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(292): Illuminate\Auth\RequestGuard->__call('getUser', Array)"
1: "#1 /vagrant/api/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Illuminate\Auth\AuthManager->__call('getUser', Array)"
2: "#2 /vagrant/api/vendor/laravel/telescope/src/Telescope.php(200): Illuminate\Support\Facades\Facade::__callStatic('getUser', Array)"
3: "#3 /vagrant/api/vendor/laravel/telescope/src/Telescope.php(275): Laravel\Telescope\Telescope::record('exception', Object(Laravel\Telescope\IncomingExceptionEntry))"
4: "#4 /vagrant/api/vendor/laravel/telescope/src/Watchers/ExceptionWatcher.php(46): Laravel\Telescope\Telescope::recordException(Object(Laravel\Telescope\IncomingExceptionEntry))"
5: "#5 /vagrant/api/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Laravel\Telescope\Watchers\ExceptionWatcher->recordException(Object(Illuminate\Log\Events\MessageLogged))"
6: "#6 /vagrant/api/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('Illuminate\\Log\\...', Array)"
7: "#7 /vagrant/api/vendor/laravel/framework/src/Illuminate/Log/Logger.php(210): Illuminate\Events\Dispatcher->dispatch('Illuminate\\Log\\...')"
8: "#8 /vagrant/api/vendor/laravel/framework/src/Illuminate/Log/Logger.php(174): Illuminate\Log\Logger->fireLogEvent('error', 'Method Illumina...', Array)"
9: "#9 /vagrant/api/vendor/laravel/framework/src/Illuminate/Log/Logger.php(87): Illuminate\Log\Logger->writeLog('error', 'Method Illumina...', Array)"
10: "#10 /vagrant/api/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(490): Illuminate\Log\Logger->error('Method Illumina...', Array)"
11: "#11 /vagrant/api/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(114): Illuminate\Log\LogManager->error('Method Illumina...', Array)"
12: "#12 /vagrant/api/app/Core/Exceptions/Handler.php(37): Illuminate\Foundation\Exceptions\Handler->report(Object(BadMethodCallException))"
13: "#13 /vagrant/api/vendor/dingo/api/src/Exception/Handler.php(77): Dinolytics\Core\Exceptions\Handler->report(Object(BadMethodCallException))"
14: "#14 /vagrant/api/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(81): Dingo\Api\Exception\Handler->report(Object(BadMethodCallException))"
15: "#15 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(BadMethodCallException))"
16: "#16 {main}"
```

Looks like at Lines 199-201 in Telescope.php
```
   if (Auth::hasUser()) {
        $entry->user(Auth::getUser());
   }
```

**Comment by Mattnmoore** [comment]
Looks like i have an old version of the code as that line is correctly calling `Auth::user()` on master. I installed this last night with `composer require laravel/telescope`, any idea why I'd get an older version?
