### ISSUE TITLE
Call to undefined method NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::shouldReport()

### ISSUE THREAD

**Issue by DonovanChan** [laravel/telescope#356]
My console command is throwing a custom exception, `App\Imports\Exceptions\InvalidDataException`, but I'm getting the following instead:

    Symfony\Component\Debug\Exception\FatalThrowableError : Call to undefined method NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::shouldReport()

This is laravel/telescope v0.1.7 running on PHP 7.1.23. I updated all Composer dependencies a moment before running this.

```
[2018-11-08 14:00:20] local.ERROR: Call to undefined method NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::shouldReport() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method NunoMaduro\\Collision\\Adapters\\Laravel\\ExceptionHandler::shouldReport() at /var/www/app/vendor/laravel/telescope/src/IncomingExceptionEntry.php:38)
[stacktrace]
#0 /var/www/app/app/Providers/TelescopeServiceProvider.php(28): Laravel\\Telescope\\IncomingExceptionEntry->isReportableException()
#1 /var/www/app/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): App\\Providers\\TelescopeServiceProvider->App\\Providers\\{closure}(Object(Laravel\\Telescope\\IncomingExceptionEntry))
#2 /var/www/app/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): Closure->__invoke(Object(Laravel\\Telescope\\IncomingExceptionEntry))
#3 /var/www/app/vendor/laravel/framework/src/Illuminate/Support/Collection.php(455): Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(Closure), 0)
#4 /var/www/app/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->every(Object(Closure))
#5 /var/www/app/vendor/laravel/telescope/src/Telescope.php(222): Illuminate\\Support\\HigherOrderCollectionProxy->__call('__invoke', Array)
#6 [internal function]: Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#7 /var/www/app/vendor/laravel/telescope/src/Telescope.php(195): call_user_func(Object(Closure))
#8 /var/www/app/vendor/laravel/telescope/src/Telescope.php(225): Laravel\\Telescope\\Telescope::withoutRecording(Object(Closure))
#9 /var/www/app/vendor/laravel/telescope/src/Telescope.php(293): Laravel\\Telescope\\Telescope::record('exception', Object(Laravel\\Telescope\\IncomingExceptionEntry))
#10 /var/www/app/vendor/laravel/telescope/src/Watchers/ExceptionWatcher.php(46): Laravel\\Telescope\\Telescope::recordException(Object(Laravel\\Telescope\\IncomingExceptionEntry))
#11 /var/www/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Laravel\\Telescope\\Watchers\\ExceptionWatcher->recordException(Object(Illuminate\\Log\\Events\\MessageLogged))
#12 /var/www/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Log\\\\...', Array)
#13 /var/www/app/vendor/laravel/framework/src/Illuminate/Log/Logger.php(210): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Log\\\\...')
#14 /var/www/app/vendor/laravel/framework/src/Illuminate/Log/Logger.php(174): Illuminate\\Log\\Logger->fireLogEvent('error', 'Row 4: The Appl...', Array)
#15 /var/www/app/vendor/laravel/framework/src/Illuminate/Log/Logger.php(87): Illuminate\\Log\\Logger->writeLog('error', 'Row 4: The Appl...', Array)
#16 /var/www/app/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(490): Illuminate\\Log\\Logger->error('Row 4: The Appl...', Array)
#17 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(114): Illuminate\\Log\\LogManager->error('Row 4: The Appl...', Array)
#18 /var/www/app/app/Exceptions/Handler.php(39): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(App\\Imports\\Exceptions\\InvalidDataException))
#19 /var/www/app/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(60): App\\Exceptions\\Handler->report(Object(App\\Imports\\Exceptions\\InvalidDataException))
#20 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(353): NunoMaduro\\Collision\\Adapters\\Laravel\\ExceptionHandler->report(Object(App\\Imports\\Exceptions\\InvalidDataException))
#21 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(124): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(App\\Imports\\Exceptions\\InvalidDataException))
#22 /var/www/app/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 {main}
"} 
```

Here's the method it's pointing to:

```php
    public function isReportableException()
    {
        return app(ExceptionHandler::class)
            ->shouldReport($this->exception);
    }
```

**Comment by themsaid** [comment]
fixed
