### ISSUE TITLE
FileNotFoundException gets thrown when uploading files

### ISSUE THREAD

**Issue by johanvanhelden** [laravel/telescope#377]
In our application we have multiple file uploads. This code works flawlessly, but as soon as we activate Telescope, we get a `FileNotFoundException`.

This is the full stack trace:

```
[2018-11-13 13:54:28] local.ERROR: The file "/tmp/phpm0ijmq" does not exist {"userId":10,"email":"redacted@redacted.nl","exception":"[object] (Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException(code: 0): The file \"/tmp/phpm0ijmq\" does not exist at /var/www/projects/redacted/vendor/symfony/http-foundation/File/File.php:37)
[stacktrace]
#0 /var/www/projects/redacted/vendor/symfony/http-foundation/File/UploadedFile.php(77): Symfony\\Component\\HttpFoundation\\File\\File->__construct('/tmp/phpm0ijmq', true)
#1 /var/www/projects/redacted/vendor/laravel/framework/src/Illuminate/Http/UploadedFile.php(120): Symfony\\Component\\HttpFoundation\\File\\UploadedFile->__construct('/tmp/phpm0ijmq', 'php-uninstall.t...', 'text/plain', 0, false)
#2 /var/www/projects/redacted/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(332): Illuminate\\Http\\UploadedFile::createFromBase(Object(Symfony\\Component\\HttpFoundation\\File\\UploadedFile))
#3 [internal function]: Illuminate\\Http\\Request->Illuminate\\Http\\Concerns\\{closure}(Object(Symfony\\Component\\HttpFoundation\\File\\UploadedFile))
#4 /var/www/projects/redacted/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(333): array_map(Object(Closure), Array)
#5 /var/www/projects/redacted/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(331): Illuminate\\Http\\Request->convertUploadedFiles(Array)
#6 [internal function]: Illuminate\\Http\\Request->Illuminate\\Http\\Concerns\\{closure}(Array)
#7 /var/www/projects/redacted/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(333): array_map(Object(Closure), Array)
#8 /var/www/projects/redacted/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(314): Illuminate\\Http\\Request->convertUploadedFiles(Array)
#9 /var/www/projects/redacted/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(184): Illuminate\\Http\\Request->allFiles()
#10 /var/www/projects/redacted/vendor/laravel/telescope/src/Watchers/RequestWatcher.php(43): Illuminate\\Http\\Request->all()
#11 /var/www/projects/redacted/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Laravel\\Telescope\\Watchers\\RequestWatcher->recordRequest(Object(Illuminate\\Foundation\\Http\\Events\\RequestHandled))
#12 /var/www/projects/redacted/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Foun...', Array)
#13 /var/www/projects/redacted/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(128): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Foun...')
#14 /var/www/projects/redacted/public_html/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#15 {main}
"} 
```

As soon as I disable telescope, the error disappears.

All our code does get executed. So the file is properly uploaded and stored in the database.

**Comment by paras-malhotra** [comment]
This seems to be a bug. My guess is the file is deleted by the time the app `terminating` callbacks are called (because perhaps it's a temporary file).

@themsaid instead of displaying complete file objects should we perhaps only have the filename displayed? I'll be happy to send across a PR if this approach is fine with you.

**Comment by themsaid** [comment]
fixed in https://github.com/laravel/telescope/pull/379

**Comment by Correspondence-emmet** [comment]
@paras-malhotra https://preprocessor.space/questions/error-in-laravel-file-not-found-exception
