### ISSUE TITLE
Error on file upload: SplFileInfo::getSize(): stat failed for /tmp/phpG0wW1T

### ISSUE THREAD

**Issue by johanvanhelden** [laravel/telescope#387]
Related to: https://github.com/laravel/telescope/issues/377

The error occurs at the line:
`'size' => ($file->getSize() / 1000).'KB',`

The file does not exist anymore, because it has been moved from `tmp` to its proper storage destination. So getting the file size from the temporary file is not possible.

```
SplFileInfo::getSize(): stat failed for /tmp/phpG0wW1T {"userId":1,"email":"redacted@redacted","exception":"[object] (RuntimeException(code: 0): SplFileInfo::getSize(): stat failed for /tmp/phpG0wW1T at /var/www/projects/redacted/vendor/laravel/telescope/src/Watchers/RequestWatcher.php:113)
[stacktrace]
#0 /var/www/projects/redacted/vendor/laravel/telescope/src/Watchers/RequestWatcher.php(113): SplFileInfo->getSize()
#1 [internal function]: Laravel\\Telescope\\Watchers\\RequestWatcher->Laravel\\Telescope\\Watchers\\{closure}(Object(Symfony\\Component\\HttpFoundation\\File\\UploadedFile), 'image')
#2 /var/www/projects/redacted/vendor/laravel/telescope/src/Watchers/RequestWatcher.php(115): array_walk_recursive(Array, Object(Closure))
#3 /var/www/projects/redacted/vendor/laravel/telescope/src/Watchers/RequestWatcher.php(43): Laravel\\Telescope\\Watchers\\RequestWatcher->input(Object(Illuminate\\Http\\Request))
#4 /var/www/projects/redacted/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Laravel\\Telescope\\Watchers\\RequestWatcher->recordRequest(Object(Illuminate\\Foundation\\Http\\Events\\RequestHandled))
#5 /var/www/projects/redacted/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Foun...', Array)
#6 /var/www/projects/redacted/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(128): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Foun...')
#7 /var/www/projects/redacted/public_html/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#8 {main}
"} 
```

**Comment by LukasSmith** [comment]
1024
