### ISSUE TITLE
Accessing Exceptions throws Error

### ISSUE THREAD

**Issue by Braunson** [laravel/telescope#447]
Trying to access `/telescope/exceptions` and in the ajax call throws this error. Running the latest Telescope release.

### Error

```
Symfony\Component\Debug\Exception\FatalThrowableError: Argument 6 passed to Laravel\Telescope\EntryResult::__construct() must be of the type array, null given, called in /home/forge/site.com/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php on line 92
```

### Full Stack

```
Symfony\Component\Debug\Exception\FatalThrowableError: Argument 6 passed to Laravel\Telescope\EntryResult::__construct() must be of the type array, null given, called in /home/forge/site.com/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php on line 92
#81 vendor/laravel/telescope/src/EntryResult.php(78): __construct
#80 vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(92): Laravel\Telescope\Storage\{closure}
#79 vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(0): array_map
#78 vendor/laravel/framework/src/Illuminate/Support/Collection.php(1007): map
#77 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php(261): map
#76 vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(94): get
#75 vendor/laravel/telescope/src/Http/Controllers/EntryController.php(31): index
#74 vendor/laravel/telescope/src/Http/Controllers/EntryController.php(0): call_user_func_array
#73 vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): callAction
#72 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): dispatch
#71 vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): runController
#70 vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): run
#69 vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Routing\{closure}
#68 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\{closure}
#67 vendor/laravel/telescope/src/Http/Middleware/Authorize.php(18): handle
#66 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#65 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#64 app/Http/Middleware/SentryContext.php(43): handle
#63 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#62 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#61 app/Http/Middleware/LogLastUserActivity.php(28): handle
#60 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#59 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#58 vendor/laravel/spark-aurelius/src/Http/Middleware/CreateFreshApiToken.php(40): handle
#57 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#56 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#55 vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): handle
#54 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#53 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#52 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): handle
#51 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#50 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#49 vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): handle
#48 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#47 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#46 vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): handle
#45 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#44 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#43 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): handle
#42 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#41 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#40 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): handle
#39 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#38 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#37 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): handle
#36 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#35 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#34 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): then
#33 vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): runRouteWithinStack
#32 vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): runRoute
#31 vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): dispatchToRoute
#30 vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): dispatch
#29 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Http\{closure}
#28 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\{closure}
#27 vendor/proengsoft/laravel-jsvalidation/src/RemoteValidationMiddleware.php(53): handle
#26 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#25 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#24 vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): handle
#23 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#22 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#21 vendor/fideloper/proxy/src/TrustProxies.php(57): handle
#20 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#19 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#18 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): handle
#17 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#16 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#15 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): handle
#14 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#13 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#12 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): handle
#11 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#10 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#9 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): handle
#8 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#7 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#6 vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(28): handle
#5 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Pipeline\{closure}
#4 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#3 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): then
#2 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): sendRequestThroughRouter
#1 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): handle
#0 public/index.php(55): null
```

**Comment by themsaid** [comment]
fixed in v1.0.7
