### ISSUE TITLE
Telescope does not work with an Oracle database

### ISSUE THREAD

**Issue by stickeerehan** [laravel/telescope#513]
Having the same issue as #214  telescope not working with Oracle. Error and stack trace below:

[2018-12-19 16:32:39] local.ERROR: oci_bind_by_name(): Invalid variable used for bind (SQL: insert into "TELESCOPE_ENTRIES" ("BATCH_ID", "CONTENT", "CREATED_AT", "TYPE", "UUID") values (8c89db33-090d-4266-b820-48986f3cc180, {"command":"list","exit_code":0,"arguments":{"command":"list","namespace":null},"options":{"raw":false,"format":"txt","help":false,"quiet":false,"verbose":false,"version":false,"ansi":false,"no-ansi":false,"no-interaction":false,"env":null},"hostname":"80f97cc23773"}, 2018-12-19 16:32:39, command, 8c89db33-0616-4441-ae1a-4738622c6227)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): oci_bind_by_name(): Invalid variable used for bind (SQL: insert into \"TELESCOPE_ENTRIES\" (\"BATCH_ID\", \"CONTENT\", \"CREATED_AT\", \"TYPE\", \"UUID\") values (8c89db33-090d-4266-b820-48986f3cc180, {\"command\":\"list\",\"exit_code\":0,\"arguments\":{\"command\":\"list\",\"namespace\":null},\"options\":{\"raw\":false,\"format\":\"txt\",\"help\":false,\"quiet\":false,\"verbose\":false,\"version\":false,\"ansi\":false,\"no-ansi\":false,\"no-interaction\":false,\"env\":null},\"hostname\":\"80f97cc23773\"}, 2018-12-19 16:32:39, command, 8c89db33-0616-4441-ae1a-4738622c6227)) at /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, ErrorException(code: 0): oci_bind_by_name(): Invalid variable used for bind at /var/www/vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8/Statement.php:491)

[stacktrace]

#0 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into \"TE...', Array, Object(Closure))
#1 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into \"TE...', Array, Object(Closure))
#2 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into \"TE...', Array)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2598): Illuminate\\Database\\Connection->insert('insert into \"TE...', Array)
#4 /var/www/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(118): Illuminate\\Database\\Query\\Builder->insert(Array)
#5 /var/www/vendor/laravel/telescope/src/Telescope.php(539): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->store(Object(Illuminate\\Support\\Collection))
#6 /var/www/vendor/laravel/telescope/src/ListensForStorageOpportunities.php(44): Laravel\\Telescope\\Telescope::store(Object(Laravel\\Telescope\\Storage\\DatabaseEntriesRepository))
#7 [internal function]: Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#8 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Object(Closure), Array)
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(75): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#12 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(967): Illuminate\\Container\\Container->call(Object(Closure))
#13 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(149): Illuminate\\Foundation\\Application->terminate()
#14 /var/www/artisan(49): Illuminate\\Foundation\\Console\\Kernel->terminate(Object(Symfony\\Component\\Console\\Input\\ArgvInput), 0)
#15 {main}

Using laravel 5.7.19, yajra/laravel-oci8 5.7.2 and telescope 1.0.10

**Comment by themsaid** [comment]
Laravel doesn't support Oracle databases out of the box, you'll need to write your own storage repo and adjust the queries.

**Comment by pszemo** [comment]
Hi,
I run Telescope with Oracle and Yajra. It is working
