### ISSUE TITLE
Error from DatabaseEntriesRepository when running seeders

### ISSUE THREAD

**Issue by Cheezykins** [laravel/telescope#557]
# Issue

When running in dev and local I use a seeder to fill my application with fake data.

The seeder creates about 50,000 records in all using Laravel's factories and the faker it provides. When running the seeder it generates the data, fills the database then sits for ages on ```Database seeding completed successfully.``` then spits out an enormous SQL query (that extends beyond my terminal's buffer, which is set to 100,000 lines, and then dies with an exception:

```
at /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1390 Prepared statement contains too many placeholders at /home/vagrant/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1390 Prepared statement contains too many placeholders at /home/vagrant/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61)
[stacktrace]
#0 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `te...', Array, Object(Closure))
#1 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into `te...', Array, Object(Closure))
#2 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `te...', Array)
#3 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2611): Illuminate\\Database\\Connection->insert('insert into `te...', Array)
#4 /home/vagrant/code/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(118): Illuminate\\Database\\Query\\Builder->insert(Array)
#5 /home/vagrant/code/vendor/laravel/telescope/src/Telescope.php(553): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->store(Object(Illuminate\\Support\\Collection))
#6 /home/vagrant/code/vendor/laravel/telescope/src/ListensForStorageOpportunities.php(44): Laravel\\Telescope\\Telescope::store(Object(Laravel\\Telescope\\Storage\\DatabaseEntriesRepository))
#7 [internal function]: Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#8 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Object(Closure), Array)
#9 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(75): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#11 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#12 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(991): Illuminate\\Container\\Container->call(Object(Closure))
#13 /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(149): Illuminate\\Foundation\\Application->terminate()
#14 /home/vagrant/code/artisan(51): Illuminate\\Foundation\\Console\\Kernel->terminate(Object(Symfony\\Component\\Console\\Input\\ArgvInput), 0)
#15 {main}
"}
```

# Environment
* Laravel 5.7.24
* Telescope 1.0.13
* Homestead 7.1.0
* PHP 7.3.1
* MySQL 5.7.5

Is there something I'm doing wrong, or is Telescopes database watcher not considering that seeding might produce enormous queries?

**Comment by Cheezykins** [comment]
For clarification, in my code I have User models, Profile models and Profile Version models. Profiles are managed by many users (they are not user profiles, they are profiles of another entity) - and a Profile has many versions.

Here is a minimum version of what I am doing to encounter this. In addition I double checked the size of the exception I get back. The exception message alone is 32MB when saved as a text file. That has to be some kind of record?


## Models

```php
class User extends Model
{
    public function profile()
    {
        return $this->belongsTo(Profile::class);
    }
}

class Profile extends Model
{
    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function versions()
    {
        return $this->hasMany(ProfileVersion::class, 'profile_id', 'id');
    }

    public function current()
    {
        return $this->belongsTo(ProfileVersion::class, 'current_id', 'id');
    }
}

class ProfileVersion extends Model
{
    public function profile()
    {
        return $this->belongsTo(Profile::class, 'profile_id');
    }
}


```

## Factories

```php
$factory->define(App\User::class, function (Faker $faker) {
    return [
        'name' => $faker->name,
    ];
});

$factory->define(App\Profile::class, function (Faker $faker) {
    return [
        'provider_id' => $faker->uuid,
        'enabled' => true,
    ];
});

$factory->define(App\ProfileVersion::class, function (Faker $faker) {
    return [
        'publication_status' => \App\PublicationStatus::PUBLISHED,
        'published_at' => $faker->dateTime,
        'profile_property_1' => 'Some text',
        'profile_property_2' => 'Some text',
        'profile_property_3' => 'Some text'
        // Profile properties are just primitives like strings, numbers and dates. No relations or complex types
    ];
});
```

## Seeder

```php
use Illuminate\Database\Seeder;

class FakeDataSeeder extends Seeder
{

    public function run(Faker\Generator $faker)
    {
        factory(\App\Profile::class, 100)
            ->create()
            ->each(function (\App\Profile $profile) {
                $versionCount = random_int(0, 5);
                $profile->users()->save(factory(\App\User::class)->make());
                for ($i = 0; $i < $versionCount; $i ++) {
                    $profile->versions()->save(
                        factory(\App\ProfileVersion::class)->make()
                    );
                }

                $profile->current()->associate(
                    $profile->versions()->save(
                            factory(\App\ProfileVersion::class)->make()
                    )
                );
                $profile->save();
            });

        }
    }
}
```

**Comment by oad-dwarf** [comment]
We are experiencing a similar problem.

Telescope needs to take the placeholder limit into account and split up the inserts into `telescope_entries`.

**Comment by themsaid** [comment]
Stop recording when you run this seeder:

```
Telescope::stopRecording()
```

**Comment by oad-dwarf** [comment]
Please re-open this issue - our usecase is different.

Not triggered by a seeder, but loading a rather large set of data from the database in one request to our API.
