### ISSUE TITLE
Telescope when on its own db connection breaks "migrate --pretend" and "migrate:fresh"

### ISSUE THREAD

**Issue by mikew1** [laravel/telescope#628]
- Telescope Version: 2.0.4
- Laravel Version: 5.8.16
- PHP Version: 7.2.14
- Database Driver & Version: pgsql

### Description:
`php artisan migrate:fresh` and `migrate --pretend` break when using telescope on a separate database connection.

You get a SQL error "table already exists" as shown below

Originally I thought this was a bug with `--pretend` flag (which I like to do before running any package migration) but I discovered it can be triggered by only `migrate:fresh`,  with `--pretend` flag never used at all.

### Steps To Reproduce:

With telescope on its own separate db connection:

`php artisan migrate`
```
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2018_01_01_000000_create_action_events_table
Migrated:  2018_01_01_000000_create_action_events_table
Migrating: 2018_08_08_100000_create_telescope_entries_table
Migrated:  2018_08_08_100000_create_telescope_entries_table
```
`php artisan migrate:rollback`
```
Rolling back: 2018_08_08_100000_create_telescope_entries_table
Rolled back:  2018_08_08_100000_create_telescope_entries_table
Rolling back: 2018_01_01_000000_create_action_events_table
Rolled back:  2018_01_01_000000_create_action_events_table
Rolling back: 2014_10_12_100000_create_password_resets_table
Rolled back:  2014_10_12_100000_create_password_resets_table
Rolling back: 2014_10_12_000000_create_users_table
Rolled back:  2014_10_12_000000_create_users_table
```

`php artisan migrate`
```
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2018_01_01_000000_create_action_events_table
Migrated:  2018_01_01_000000_create_action_events_table
Migrating: 2018_08_08_100000_create_telescope_entries_table
Migrated:  2018_08_08_100000_create_telescope_entries_table
```

As you can see all the above is working fine.

**but**

```
~ $ php artisan migrate:fresh
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > y

Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2018_01_01_000000_create_action_events_table
Migrated:  2018_01_01_000000_create_action_events_table
Migrating: 2018_08_08_100000_create_telescope_entries_table
[2019-05-10 18:38:11] production.ERROR: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "telescope_entries" already exists (SQL: create table "telescope_entries" ("sequence" bigserial primary key not null, "uuid" uuid not null, "batch_id" uuid not null, "family_hash" varchar(255) null, "should_display_on_index" boolean not null default '1', "type" varchar(20) not null, "content" text not null, "created_at" timestamp(0) without time zone null)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42P07): SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation \"telescope_entries\" already exists (SQL: create table \"telescope_entries\" (\"sequence\" bigserial primary key not null, \"uuid\" uuid not null, \"batch_id\" uuid not null, \"family_hash\" varchar(255) null, \"should_display_on_index\" boolean not null default '1', \"type\" varchar(20) not null, \"content\" text not null, \"created_at\" timestamp(0) without time zone null)) at /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: 42P07): SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation \"telescope_entries\" already exists at /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458)
[stacktrace]
#0 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('create table \"t...', Array, Object(Closure))
#1 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('create table \"t...', Array, Object(Closure))
#2 /app/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(97): Illuminate\\Database\\Connection->statement('create table \"t...')
#3 /app/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(278): Illuminate\\Database\\Schema\\Blueprint->build(Object(Illuminate\\Database\\PostgresConnection), Object(Illuminate\\Database\\Schema\\Grammars\\PostgresGrammar))
#4 /app/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(167): Illuminate\\Database\\Schema\\Builder->build(Object(Illuminate\\Database\\Schema\\Blueprint))
#5 /app/telescope/src/Storage/migrations/2018_08_08_100000_create_telescope_entries_table.php(48): Illuminate\\Database\\Schema\\Builder->create('telescope_entri...', Object(Closure))
#6 /app/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(385): CreateTelescopeEntriesTable->up()
#7 /app/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}(Object(Illuminate\\Database\\PostgresConnection))
#8 /app/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(393): Illuminate\\Database\\Connection->transaction(Object(Closure))
#9 /app/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(197): Illuminate\\Database\\Migrations\\Migrator->runMigration(Object(CreateTelescopeEntriesTable), 'up')
#10 /app/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(164): Illuminate\\Database\\Migrations\\Migrator->runUp('/app/telescope/...', 1, false)
#11 /app/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(111): Illuminate\\Database\\Migrations\\Migrator->runPending(Array, Array)
#12 /app/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(71): Illuminate\\Database\\Migrations\\Migrator->run(Array, Array)
#13 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#14 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#15 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#19 /app/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#20 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#21 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(198): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#22 /app/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/FreshCommand.php(61): Illuminate\\Console\\Command->call('migrate', Array)
#23 [internal function]: Illuminate\\Database\\Console\\Migrations\\FreshCommand->handle()
#24 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#25 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#26 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#27 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#28 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#29 /app/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#30 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#31 /app/vendor/symfony/console/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /app/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Migrations\\FreshCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /app/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 /app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 {main}
"} 


```

I have telescope installed as a path repository in same way as nova (and wink), that shouldn't make any difference as far as I know though.

**I do not get this error when I use the same default pgsql database connection for telescope**.   It's only when I use a separate db connection that I get the above error.

If I use **only** `artisan migrate` and `artisan migrate:rollback`, and **_never_** `migrate:fresh`, in my workflow, then there is **no problem**, even when using a separate db connection.

**But** if I am using a separate db connection, and I use `migrate:fresh` and/or `migrate --pretend` in my workflow, it will soon error out as above.

### A thought

It seems maybe wink has a better design?... In wink, a separate connection is _assumed_, and there's a separate command to run its own migrations, unlike here so we get this problem... ?

**Comment by mikew1** [comment]
What's the intended purpose of 

```
    /**
     * Indicates if Telescope migrations will be run.
     *
     * @var bool
     */
    public static $runsMigrations = true;
```

in the file src/Telescope.php?

If I switched that to false after running the migration (on the separate connection) the first time, that might fix it, but altering source is obviously bad.  I wonder how to fix this properly.

Thanks
Mike

**Comment by mikew1** [comment]
I just saw the following in telescope ServiceProvider:

```
    /**
     * Determine if the application is running an approved command.
     *
     * @param  \Illuminate\Foundation\Application  $app
     * @return bool
     */
    protected static function runningApprovedArtisanCommand($app)
    {
        return $app->runningInConsole() && ! in_array(
            $_SERVER['argv'][1] ?? null,
            array_merge([
                // 'migrate',
                'migrate:rollback',
                'migrate:fresh',
                // 'migrate:refresh',
                'migrate:reset',
                'migrate:install',
                'package:discover',
                'queue:listen',
                'queue:work',
                'horizon',
                'horizon:work',
                'horizon:supervisor',
            ], config('telescope.ignoreCommands', []), config('telescope.ignore_commands', []))
        );
    }
```
Questions
1. Can we add `migrate --pretend` to approved commands (does it respect flags?)
2. A wild guess is migrate:fresh is removed there because you might not want a second db connection being wiped? (I can't envisage use cases with any certainty to confirm that).
3. migrate:fresh is approved above but that's one that's failing as it doesn't drop the db on 2nd connection if using one.
4. `migrate` itself is not in the approved list; so maybe I don't know what's going on here after all.

5. Maybe I've misunderstood the above completely and this is unique to telescope and what it records, not how it behaves itself, as a package?

**Comment by MerrySean** [comment]
Hey :D

have you fixed this? found any alternatives?

**Comment by mikew1** [comment]
That looks good - I hadn't thought of reaching for cmd line options to `migrate`. Telescope docs didn't mention this though (which would be why I didn't), so, I'll try to do a PR on the docs if I get back to this and fix it.  Or feel free to do that yourself if you get clarity :) thanks 👍

**Comment by mikew1** [comment]
**Update**

I see that telescope greatly limits the data gathered in production by default.

While you can gather more, I see it's not intended to be a 'logging' tool, rather a debug assistant.
With that clarified, it doesn't seem so crucial to use a separate db connection.

It is possible though, but I've got going with it now just settling on using the same connection.

Interesting that the problem I think I had here was one of expectations...
So it's an education/docs/laracasts type thing that could have solved this...

The lesson I take from this is that when using a tool, especially one which is relatively new, it's important to really try to understand well the intended usage that the authors have in mind, and not try to deviate much or at all from that. The newer the tool, the more important this is.

Looks a great tool, thanks.
