### ISSUE TITLE
Model attribute accessor crashes RequestWatcher when model is serialized.

### ISSUE THREAD

**Issue by trip-somers** [laravel/telescope#647]
- Telescope Version: 2.0.4
- Laravel Version: 5.8.17
- PHP Version: 7.2.19
- Database Driver & Version: PostgreSQL 11.2.1

### Description: A model attribute accessor that returns `$this->created_at->diffForHumans()` and is added to the model's `$appends` array results in an ErrorException because `created_at` is somehow null when the RequestWatcher serializes the collection for an index page request. (There are no null values in the database for that column. For now, I have patched the accessor to do a null check before calling `diffForHumans()`.)

The catch? This only happens in production where the watchers are active but the filter method blocks most entries. (We are using the default/example filter method from the documention.) The stage server and the development checkouts do not have this problem.

Stack Trace:
```
[stacktrace]
#0 /var/www/develop/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(446): App\\Data\\Models\\Audit->getElapsedTimeAttribute(NULL)
#1 /var/www/develop/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(458): Illuminate\\Database\\Eloquent\\Model->mutateAttribute('elapsed_time', NULL)
#2 /var/www/develop/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(111): Illuminate\\Database\\Eloquent\\Model->mutateAttributeForArray('elapsed_time', NULL)
#3 /var/www/develop/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1084): Illuminate\\Database\\Eloquent\\Model->attributesToArray()
#4 /var/www/develop/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1113): Illuminate\\Database\\Eloquent\\Model->toArray()
#5 /var/www/develop/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1926): Illuminate\\Database\\Eloquent\\Model->jsonSerialize()
#6 [internal function]: Illuminate\\Support\\Collection->Illuminate\\Support\\{closure}(Object(App\\Data\\Models\\Audit))
#7 /var/www/develop/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1934): array_map(Object(Closure), Array)
#8 [internal function]: Illuminate\\Support\\Collection->jsonSerialize()
#9 /var/www/develop/vendor/laravel/telescope/src/Watchers/RequestWatcher.php(194): json_encode(Object(Illuminate\\Database\\Eloquent\\Collection))
#10 [internal function]: Laravel\\Telescope\\Watchers\\RequestWatcher->Laravel\\Telescope\\Watchers\\{closure}(Object(Illuminate\\Database\\Eloquent\\Collection), 'auditable_types')
#11 /var/www/develop/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1120): array_map(Object(Closure), Array, Array)
#12 /var/www/develop/vendor/laravel/telescope/src/Watchers/RequestWatcher.php(199): Illuminate\\Support\\Collection->map(Object(Closure))
#13 /var/www/develop/vendor/laravel/telescope/src/Watchers/RequestWatcher.php(160): Laravel\\Telescope\\Watchers\\RequestWatcher->extractDataFromView(Object(Illuminate\\View\\View))
#14 /var/www/develop/vendor/laravel/telescope/src/Watchers/RequestWatcher.php(51): Laravel\\Telescope\\Watchers\\RequestWatcher->response(Object(Illuminate\\Http\\Response))
#15 /var/www/develop/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): Laravel\\Telescope\\Watchers\\RequestWatcher->recordRequest(Object(Illuminate\\Foundation\\Http\\Events\\RequestHandled))
#16 /var/www/develop/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(196): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Foun...', Array)
#17 /var/www/develop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(128): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Foun...')
#18 /var/www/develop/public/index.php(59): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#19 {main}
```

### Steps To Reproduce:
1. Create a model with an attribute accessor that returns a derivative of another attribute.
2. Store a few model instances in your database.
3. Create an index route that will serve a collection of this model.
-or-
1 & 2 & 3. Add an attribute accessor that returns a derivative of another attribute to an existing model that already has an index route.
-then-
4. Add the accessor's attribute to the model's `$appends` array.
5. Make an HTTP request the index page.

**Comment by taylorotwell** [comment]
Can't seem to recreate this.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/463230/70353762-bf4b4000-1833-11ea-970d-36081b737fb2.png">

**Comment by trip-somers** [comment]
I do not remember even opening this, so I guess it hasn't been much of a problem since originally posted. If I did anything to "solve" it, I sure don't remember what it was.
