### ISSUE TITLE
Disabled Telescope still trying to query database

### ISSUE THREAD

**Issue by mityukov** [laravel/telescope#751]
- Telescope Version: v2.0.6
- Laravel Version: v5.8.33
- PHP Version: 7.3.8
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.27 (not sure what ":database driver" means exactly)

### Description:

I have Telescope disabled on production site:

1. config/telescope.php:
```
    'enabled' => env('TELESCOPE_ENABLED', false),`
```

2. config/app.php:
```
    // App\Providers\TelescopeServiceProvider::class,
```
(commented out)

Still, there are some MySQL queries, related to telescope tables. I noticed them by chance in a Sentry report =)

Queries like:
```
select `tag` from `telescope_monitoring`
```

Here's full trace (a side question: is there way to "deduct" which certain job is was from a trace like this?):
```
ErrorException: Warning: PDO::prepare(): MySQL server has gone away
#35 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(61): Doctrine\DBAL\Driver\PDOConnection::prepare
#34 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection::Illuminate\Database\{closure}
#33 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection::runQueryCallback
#32 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection::run
#31 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\Database\Connection::select
#30 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2130): Illuminate\Database\Query\Builder::runSelect
#29 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2324): Illuminate\Database\Query\Builder::Illuminate\Database\Query\{closure}
#28 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2604): Illuminate\Database\Query\Builder::onceWithColumns
#27 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2326): Illuminate\Database\Query\Builder::pluck
#26 /vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(281): Laravel\Telescope\Storage\DatabaseEntriesRepository::monitoring
#25 /vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(253): Laravel\Telescope\Storage\DatabaseEntriesRepository::loadMonitoredTags
#24 /vendor/laravel/telescope/src/Telescope.php(195): Laravel\Telescope\Telescope::startRecording
#23 /vendor/laravel/telescope/src/ListensForStorageOpportunities.php(57): Laravel\Telescope\Telescope::Laravel\Telescope\{closure}
#22 /vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): Illuminate\Events\Dispatcher::Illuminate\Events\{closure}
#21 /vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(196): Illuminate\Events\Dispatcher::dispatch
#20 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(464): Illuminate\Queue\Worker::raiseBeforeJobEvent
#19 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(324): Illuminate\Queue\Worker::process
#18 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(283): Illuminate\Queue\Worker::runJob
#17 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker::daemon
#16 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Console\WorkCommand::runWorker
#15 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand::handle
#14 /vendor/laravel/horizon/src/Console/WorkCommand.php(46): Laravel\Horizon\Console\WorkCommand::handle
#13 [internal](0): call_user_func_array
#12 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#11 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\BoundMethod::callBoundMethod
#10 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::call
#9 /vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\Container\Container::call
#8 /vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Console\Command::execute
#7 /vendor/symfony/console/Command/Command.php(255): Symfony\Component\Console\Command\Command::run
#6 /vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Illuminate\Console\Command::run
#5 /vendor/symfony/console/Application.php(921): Symfony\Component\Console\Application::doRunCommand
#4 /vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application::doRun
#3 /vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application::run
#2 /vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Illuminate\Console\Application::run
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\Foundation\Console\Kernel::handle
#0 /artisan(37): null
```

**Comment by michael-schaefer-eu** [comment]
Have you cleared your config cache?

`php artisan config:clear`

**Comment by mityukov** [comment]
> Have you cleared your config cache?
> 
> `php artisan config:clear`

It's in my deployment script, so, yes.
