### ISSUE TITLE
Date format specified in the query grammar is ignored on insert

### ISSUE THREAD

**Issue by giulianoriccio** [laravel/telescope#809]
- Telescope Version: 2.1.2
- Laravel Version: 6.10.1
- PHP Version: 7.2.10

### Description:
The date format of the value for the field `created_at` of the table `telescope_entries` doesn't match what is specified in the query grammar when inserting new rows.

In telescope the async requests will fail with a 500 error due to the mismatch (ex: `/telescope/telescope-api/requests?tag=&before=&take=50&family_hash=` or `/telescope/telescope-api/exceptions?tag=&before=&take=50&family_hash=`):

```
[2020-01-09 12:49:36] local.ERROR: Trailing data {"userId":1,"exception":"[object] (InvalidArgumentException(code: 0): Trailing data at /vagrant/www/vhosts/hermes.rifraf.it/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:576)
[stacktrace]
#0 /vagrant/www/vhosts/hermes.rifraf.it/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(598): Carbon\\Carbon::rawCreateFromFormat('U', '2020-01-09 12:4...', NULL)
#1 /vagrant/www/vhosts/hermes.rifraf.it/vendor/laravel/framework/src/Illuminate/Support/DateFactory.php(217): Carbon\\Carbon::createFromFormat('U', '2020-01-09 12:4...')
#2 /vagrant/www/vhosts/hermes.rifraf.it/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Support\\DateFactory->__call('createFromForma...', Array)
#3 /vagrant/www/vhosts/hermes.rifraf.it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(813): Illuminate\\Support\\Facades\\Facade::__callStatic('createFromForma...', Array)
#4 /vagrant/www/vhosts/hermes.rifraf.it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(365): Illuminate\\Database\\Eloquent\\Model->asDateTime('2020-01-09 12:4...')
#5 /vagrant/www/vhosts/hermes.rifraf.it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(323): Illuminate\\Database\\Eloquent\\Model->getAttributeValue('created_at')
#6 /vagrant/www/vhosts/hermes.rifraf.it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1523): Illuminate\\Database\\Eloquent\\Model->getAttribute('created_at')
#7 /vagrant/www/vhosts/hermes.rifraf.it/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(105): Illuminate\\Database\\Eloquent\\Model->__get('created_at')
...
```

Of course I've also tried changing the table field type but in that case the insert will fail.

### Steps To Reproduce:

In my case I've extended the MySqlGrammar this way:

```php
namespace App\Database\Query\Grammars;

class MySqlGrammar extends \Illuminate\Database\Query\Grammars\MySqlGrammar
{
    public function getDateFormat()
    {
        return 'U';
    }
}
```

and registered it in the AppServiceProvider:

```php
class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        DB::connection()->setQueryGrammar(new \App\Database\Query\Grammars\MySqlGrammar);
    }
```

As a temporary solution I've wrapped the setQueryGrammar in a condition:
```php
        if (Telescope::isRecording()) {
            DB::connection()->setQueryGrammar(new \App\Database\Query\Grammars\MySqlGrammar);
        }
```

**Comment by driesvints** [comment]
Afaik this shouldn't matter as this is handled by Telescope itself?

**Comment by themsaid** [comment]
I don't understand your problem.

**Comment by giulianoriccio** [comment]
telescope breaks when customizing the date format used by eloquent using the query grammar

**Comment by pcfjojo** [comment]
Infact, we too face issues with MSSQL database dateType. 
Better if possible to overide the telescope models or globally set datatype.

**Comment by driesvints** [comment]
Closing this as we don't support extending query grammar with the packages sorry.

**Comment by Ademking** [comment]
> Infact, we too face issues with MSSQL database dateType.
> Better if possible to overide the telescope models or globally set datatype.

@pcfjojo Please how did you fix this error ?
I'm using telescope with MSSQL. 
Thanks
