### ISSUE TITLE
Error on specific artisan command since v3

### ISSUE THREAD

**Issue by clmntgr** [laravel/telescope#831]
- Telescope Version: 3.0.0
- Laravel Version: 6.16.0
- PHP Version: 7.4.3
- Database Driver & Version: Postgres 10

### Description:

Since last telescope update I got this error when running `php artisan migrate` (even if I have no migration), I think it's related to telescope monitoring artisan commands. I have the same error if I run `php artisan telescope:publish`.

```
[2020-02-21 13:17:06] local.ERROR: Array to string conversion {"exception":"[object] (ErrorException(code: 0): Array to string conversion at /vendor/laravel/framework/src/Illuminate/Support/Str.php:419)
[stacktrace]
#0 /vendor/laravel/framework/src/Illuminate/Support/Str.php(419): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Array to string...', '/Users/clmnt/Co...', 419, Array)
#1 /vendor/laravel/framework/src/Illuminate/Database/QueryException.php(56): Illuminate\\Support\\Str::replaceArray('?', Array, 'insert into \"te...')
#2 /vendor/laravel/framework/src/Illuminate/Database/QueryException.php(39): Illuminate\\Database\\QueryException->formatMessage('insert into \"te...', Array, Object(ErrorException))
#3 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(670): Illuminate\\Database\\QueryException->__construct('insert into \"te...', Array, Object(ErrorException))
#4 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback('insert into \"te...', Array, Object(Closure))
#5 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(464): Illuminate\\Database\\Connection->run('insert into \"te...', Array, Object(Closure))
#6 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\\Database\\Connection->statement('insert into \"te...', Array)
#7 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2651): Illuminate\\Database\\Connection->insert('insert into \"te...', Array)
#8 /vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(199): Illuminate\\Database\\Query\\Builder->insert(Array)
#9 /vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(176): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->Laravel\\Telescope\\Storage\\{closure}(Object(Illuminate\\Support\\Collection), 0)
#10 /vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(200): Illuminate\\Support\\Collection->each(Object(Closure))
#11 /vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(151): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->storeTags(Object(Illuminate\\Support\\Collection))
#12 /vendor/laravel/telescope/src/Telescope.php(567): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->store(Object(Illuminate\\Support\\Collection))
#13 /vendor/laravel/telescope/src/ListensForStorageOpportunities.php(44): Laravel\\Telescope\\Telescope::store(Object(Laravel\\Telescope\\Storage\\DatabaseEntriesRepository))
#14 [internal function]: Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#15 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Object(Closure), Array)
#16 /vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(78): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#18 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#19 /vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#20 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1047): Illuminate\\Container\\Container->call(Object(Closure))
#21 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(158): Illuminate\\Foundation\\Application->terminate()
#22 /artisan(51): Illuminate\\Foundation\\Console\\Kernel->terminate(Object(Symfony\\Component\\Console\\Input\\ArgvInput), 0)
#23 {main}
"}
```

If I downgrade to v2.1.6, there is no issue

### Steps To Reproduce:

1) Upgrade to Telescope v3
2) Run `php artisan migrate`

**Comment by themsaid** [comment]
I can't replicate on a fresh Laravel 6 and Telescope 3.

**Comment by clmntgr** [comment]
If I can provide anything to debug this one tell me

**Comment by gdebrauwer** [comment]
@themsaid @clmntgr  I also have the same issue. it seems to be related to tagging.

I had the following code in my TelescopeServiceProvider:
```php
Telescope::tag(function (IncomingEntry $entry) {
    if ($entry->type === 'request') {
        return [
            'status:' . $entry->content['response_status'],
            'uri:' . $entry->content['uri'],
        ];
    }

    return [];
});
```

If I return an empty string instead of an empty array, the exception is not thrown: 
```php
Telescope::tag(function (IncomingEntry $entry) {
    if ($entry->type === 'request') {
        return [
            'status:' . $entry->content['response_status'],
            'uri:' . $entry->content['uri'],
        ];
    }

    return '';
});
```

This is bug, because in the docs an empty array is used (https://laravel.com/docs/6.x/telescope#tagging)

**Comment by clmntgr** [comment]
I'm returning an empty array too in my tag function.

**Comment by clmntgr** [comment]
Fixed in https://github.com/laravel/telescope/pull/839
