### ISSUE TITLE
Unable to use a custom cache driver while having telescope enabled

### ISSUE THREAD

**Issue by aocneanu** [laravel/telescope#988]
- Telescope Version: 4.3.1
- Laravel Version: 8.16..1
- PHP Version: 7.4.12
- Database Driver & Version: MySQL 8.0.22

### Description:
I created a custom cache driver that is registered in the AppServiceProvider and I want to use it as default (env / config).

Apparently I cannot do that while having telescope enabled, because from the TelescopeServiceProvider (`Telescope::start($this->app)` -> `RegistersWatchers` -> `DumpWatchers::register()) that is loaded before AppServiceProvider a call is made to the cache (CacheManager is trying to resolve a custom driver but the driver was not registered yet)

Is this expected?

### Steps To Reproduce:
Create a custom cache driver
Register it according to the docs in the AppServiceProvider
Set TELESCOPE_ENABLED=1 in .env
Try to boot the framework (eg: tinker)

StackTrace:

```php
[2020-11-26 11:28:31] local.ERROR: Driver [chain] is not supported. {"exception":"[object] (InvalidArgumentException(code: 0): Driver [chain] is not supported. at /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:109)
[stacktrace]
#0 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(82): Illuminate\\Cache\\CacheManager->resolve('chain')
#1 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(60): Illuminate\\Cache\\CacheManager->get('chain')
#2 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(400): Illuminate\\Cache\\CacheManager->store()
#3 /Users/adi/code/enso/vendor/laravel/telescope/src/Watchers/DumpWatcher.php(43): Illuminate\\Cache\\CacheManager->__call('get', Array)
#4 /Users/adi/code/enso/vendor/laravel/telescope/src/RegistersWatchers.php(48): Laravel\\Telescope\\Watchers\\DumpWatcher->register(Object(Illuminate\\Foundation\\Application))
#5 /Users/adi/code/enso/vendor/laravel/telescope/src/Telescope.php(143): Laravel\\Telescope\\Telescope::registerWatchers(Object(Illuminate\\Foundation\\Application))
#6 /Users/adi/code/enso/vendor/laravel/telescope/src/TelescopeServiceProvider.php(31): Laravel\\Telescope\\Telescope::start(Object(Illuminate\\Foundation\\Application))
#7 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Telescope\\TelescopeServiceProvider->boot()
#8 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#10 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(869): Illuminate\\Container\\Container->call(Array)
#13 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(850): Illuminate\\Foundation\\Application->bootProvider(Object(Laravel\\Telescope\\TelescopeServiceProvider))
#14 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Laravel\\Telescope\\TelescopeServiceProvider), 97)
#15 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): array_walk(Array, Object(Closure))
#16 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#17 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#18 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#19 /Users/adi/code/enso/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#20 /Users/adi/code/enso/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"} 
```

**Comment by driesvints** [comment]
Yeah this does seems problematic. I don't have a solution right away so appreciating an extra pair of eyes.

**Comment by aocneanu** [comment]
Besides `DumpWatcher` that could eventually use the file store, `CacheWatcher` has the same issue and in its case we will want access to the default store.

A solution would be finding a way to set ASP load priority at the framework level and put the package's `TelescopeServiceProvider` to the end of the list. This might save other awkward scenarios as well, so it could be a nice feature.

Another solution could be removing the autoload for `Laravel\Telescope\TelescopeServiceProvider` and consolidating it somehow with `Laravel\Telescope\TelescopeApplicationServiceProvider` and then relying only on the local `App\Providers\TelescopeServiceProvider` that could extend the new one. This would solve the load problem. I did not study the implications here.

**Comment by driesvints** [comment]
The later sounds good but it would require a really big breaking change.

**Comment by raftx24** [comment]
I guess we can wrap the boot method in the $this->app->booted(function () {}). as below
```
$this->app->booted(function () {
            if (! config('telescope.enabled')) {
                return;
            }

            Route::middlewareGroup('telescope', config('telescope.middleware', []));

            $this->registerRoutes();
            $this->registerMigrations();
            $this->registerPublishing();

            Telescope::start($this->app);
            Telescope::listenForStorageOpportunities($this->app);

            $this->loadViewsFrom(
                __DIR__.'/../resources/views', 'telescope'
            );
        });
```

**Comment by aocneanu** [comment]
I guess wrapping Telescope:start and listen in app->booted should be enough.

**Comment by driesvints** [comment]
That seems like a good solution to me as well. Can any of you PR that?

**Comment by aocneanu** [comment]
@driesvints found [another solution](https://github.com/laravel-enso/cache-chain/pull/3/files) for our use case which seems to me more robust, because it avoids this situation for any potential package that might do what telescope is doing.

Do you think that it would make sense to do a PR to laravel docs instead or I'm missing somthing out?

```php
Cache::extend('mongo', function ($app) {
    return Cache::repository(new MongoStore);
});
```

could become

```php
$this->app->booting(function () {
    Cache::extend('mongo', function ($app) {
        return Cache::repository(new MongoStore);
    });
});
```

**Comment by driesvints** [comment]
Ah yes that's smart actually. If you want you can send a PR to the docs for that.
